#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/


// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.9.0.
//
// This code was generated with the following options:
//
//  {'epsilon': 1e-14,
//   'scalar_type': <class 'numpy.float64'>,
//   'sum_factorization': False,
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'verbosity': 30}

#include <math.h>
#include <stdalign.h>
#include <stdlib.h>
#include <string.h>
#include <ufcx.h>



// Code for integral integral_687b20576e5f2ca5250b3496455c7a6f97a42ed6

void tabulate_tensor_integral_687b20576e5f2ca5250b3496455c7a6f97a42ed6(double* restrict A,
                                    const double* restrict w,
                                    const double* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation)
{
// Quadrature rules
static const double weights_fad[4] = {0.04166666666666666, 0.04166666666666666, 0.04166666666666666, 0.04166666666666666};
// Precomputed values of basis functions and precomputations
// FE* dimensions: [permutation][entities][points][dofs]
static const double FE1_C0_D100_Qfad[1][1][1][4] = {{{{-1.0, 1.0, 0.0, 0.0}}}};
static const double FE1_C1_D010_Qfad[1][1][1][4] = {{{{-1.0, 0.0, 1.0, 0.0}}}};
static const double FE1_C2_D001_Qfad[1][1][1][4] = {{{{-1.0, 0.0, 0.0, 1.0}}}};
static const double FE3_C0_Qfad[1][1][4][4] = {{{{0.1381966011250091, 0.5854101966249688, 0.1381966011250109, 0.1381966011250109},
  {0.1381966011250091, 0.138196601125011, 0.585410196624969, 0.1381966011250109},
  {0.1381966011250091, 0.138196601125011, 0.138196601125011, 0.585410196624969},
  {0.585410196624967, 0.1381966011250109, 0.1381966011250109, 0.1381966011250109}}}};
// ------------------------ 
// Section: Jacobian
// Inputs: FE1_C1_D010_Qfad, coordinate_dofs, FE1_C2_D001_Qfad, FE1_C0_D100_Qfad
// Outputs: J_c1, J_c6, J_c5, J_c8, J_c2, J_c3, J_c0, J_c4, J_c7
double J_c0 = 0.0;
double J_c4 = 0.0;
double J_c8 = 0.0;
double J_c5 = 0.0;
double J_c7 = 0.0;
double J_c3 = 0.0;
double J_c6 = 0.0;
double J_c1 = 0.0;
double J_c2 = 0.0;
{
  for (int ic = 0; ic < 4; ++ic)
  {
    J_c0 += coordinate_dofs[(ic) * 3] * FE1_C0_D100_Qfad[0][0][0][ic];
    J_c4 += coordinate_dofs[(ic) * 3 + 1] * FE1_C1_D010_Qfad[0][0][0][ic];
    J_c8 += coordinate_dofs[(ic) * 3 + 2] * FE1_C2_D001_Qfad[0][0][0][ic];
    J_c5 += coordinate_dofs[(ic) * 3 + 1] * FE1_C2_D001_Qfad[0][0][0][ic];
    J_c7 += coordinate_dofs[(ic) * 3 + 2] * FE1_C1_D010_Qfad[0][0][0][ic];
    J_c3 += coordinate_dofs[(ic) * 3 + 1] * FE1_C0_D100_Qfad[0][0][0][ic];
    J_c6 += coordinate_dofs[(ic) * 3 + 2] * FE1_C0_D100_Qfad[0][0][0][ic];
    J_c1 += coordinate_dofs[(ic) * 3] * FE1_C1_D010_Qfad[0][0][0][ic];
    J_c2 += coordinate_dofs[(ic) * 3] * FE1_C2_D001_Qfad[0][0][0][ic];
  }
}
// ------------------------ 
double sp_fad_0 = J_c4 * J_c8;
double sp_fad_1 = J_c5 * J_c7;
double sp_fad_2 = -sp_fad_1;
double sp_fad_3 = sp_fad_0 + sp_fad_2;
double sp_fad_4 = J_c0 * sp_fad_3;
double sp_fad_5 = J_c3 * J_c8;
double sp_fad_6 = J_c5 * J_c6;
double sp_fad_7 = -sp_fad_6;
double sp_fad_8 = sp_fad_5 + sp_fad_7;
double sp_fad_9 = -J_c1;
double sp_fad_10 = sp_fad_8 * sp_fad_9;
double sp_fad_11 = sp_fad_4 + sp_fad_10;
double sp_fad_12 = J_c3 * J_c7;
double sp_fad_13 = J_c4 * J_c6;
double sp_fad_14 = -sp_fad_13;
double sp_fad_15 = sp_fad_12 + sp_fad_14;
double sp_fad_16 = J_c2 * sp_fad_15;
double sp_fad_17 = sp_fad_11 + sp_fad_16;
double sp_fad_18 = fabs(sp_fad_17);
double sp_fad_19 = 2320.0 * sp_fad_18;
for (int iq = 0; iq < 4; ++iq)
{
  // ------------------------ 
  // Section: Intermediates
  // Inputs: 
  // Outputs: fw0
  double fw0 = 0;
  {
    fw0 = sp_fad_19 * weights_fad[iq];
  }
  // ------------------------ 
  // ------------------------ 
  // Section: Tensor Computation
  // Inputs: fw0, FE3_C0_Qfad
  // Outputs: A
  {
    double temp_0[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_0[j] = fw0 * FE3_C0_Qfad[0][0][iq][j];
    }
    double temp_1[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_1[j] = fw0 * FE3_C0_Qfad[0][0][iq][j];
    }
    double temp_2[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_2[j] = fw0 * FE3_C0_Qfad[0][0][iq][j];
    }
    for (int j = 0; j < 4; ++j)
    {
      for (int i = 0; i < 4; ++i)
      {
        A[12 * (3 * (i)) + 3 * (j)] += FE3_C0_Qfad[0][0][iq][i] * temp_0[j];
        A[12 * (3 * (i) + 1) + (3 * (j) + 1)] += FE3_C0_Qfad[0][0][iq][i] * temp_1[j];
        A[12 * (3 * (i) + 2) + (3 * (j) + 2)] += FE3_C0_Qfad[0][0][iq][i] * temp_2[j];
      }
    }
  }
  // ------------------------ 
}

}



ufcx_integral integral_687b20576e5f2ca5250b3496455c7a6f97a42ed6 =
{
  .enabled_coefficients = NULL,
  .tabulate_tensor_float32 = NULL,
  .tabulate_tensor_float64 = tabulate_tensor_integral_687b20576e5f2ca5250b3496455c7a6f97a42ed6,
  .tabulate_tensor_complex64 = NULL,
  .tabulate_tensor_complex128 = NULL,
  .needs_facet_permutations = false,
  .coordinate_element_hash = UINT64_C(0),
};

// End of code for integral integral_687b20576e5f2ca5250b3496455c7a6f97a42ed6

// Code for form form_22e951a9bc4b20597ab54228324b1cdd275d43cb


uint64_t finite_element_hashes_form_22e951a9bc4b20597ab54228324b1cdd275d43cb[2] = {UINT64_C(0), UINT64_C(0)};
int form_integral_offsets_form_22e951a9bc4b20597ab54228324b1cdd275d43cb[4] = {0, 1, 1, 1};
static ufcx_integral* form_integrals_form_22e951a9bc4b20597ab54228324b1cdd275d43cb[1] = {&integral_687b20576e5f2ca5250b3496455c7a6f97a42ed6};
int form_integral_ids_form_22e951a9bc4b20597ab54228324b1cdd275d43cb[1] = {-1};




ufcx_form form_22e951a9bc4b20597ab54228324b1cdd275d43cb =
{

  .signature = "bd8baa1d9097a333f7c8a5cdc19f77fd918a0955288a3e3e99a39d7db64d83874fcb99e3ce6f61a35d8a280c414cf2b65ce1fa0b17624a422e9bcf6ee60598d4",
  .rank = 2,
  .num_coefficients = 0,
  .num_constants = 0,
  .original_coefficient_positions = NULL,

  .coefficient_name_map = NULL,
  .constant_name_map = NULL,

  .finite_element_hashes = finite_element_hashes_form_22e951a9bc4b20597ab54228324b1cdd275d43cb,

  .form_integrals = form_integrals_form_22e951a9bc4b20597ab54228324b1cdd275d43cb,
  .form_integral_ids = form_integral_ids_form_22e951a9bc4b20597ab54228324b1cdd275d43cb,
  .form_integral_offsets = form_integral_offsets_form_22e951a9bc4b20597ab54228324b1cdd275d43cb
};

// Alias name
ufcx_form* form_libffcx_forms_006c7f09c00364dbb57168308ad49c342d0e249f_0 = &form_22e951a9bc4b20597ab54228324b1cdd275d43cb;

// End of code for form form_22e951a9bc4b20597ab54228324b1cdd275d43cb


/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 55), // void()(double *, double const *, double const *, double const *, int const *, uint8_t const *)
/*  1 */ _CFFI_OP(_CFFI_OP_POINTER, 38), // double *
/*  2 */ _CFFI_OP(_CFFI_OP_POINTER, 38), // double const *
/*  3 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/*  4 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/*  5 */ _CFFI_OP(_CFFI_OP_POINTER, 42), // int const *
/*  6 */ _CFFI_OP(_CFFI_OP_POINTER, 50), // uint8_t const *
/*  7 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  8 */ _CFFI_OP(_CFFI_OP_FUNCTION, 55), // void()(double _Complex *, double _Complex const *, double _Complex const *, double const *, int const *, uint8_t const *)
/*  9 */ _CFFI_OP(_CFFI_OP_POINTER, 37), // double _Complex *
/* 10 */ _CFFI_OP(_CFFI_OP_POINTER, 37), // double _Complex const *
/* 11 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 12 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/* 13 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 14 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 15 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 16 */ _CFFI_OP(_CFFI_OP_FUNCTION, 55), // void()(float *, float const *, float const *, float const *, int const *, uint8_t const *)
/* 17 */ _CFFI_OP(_CFFI_OP_POINTER, 40), // float *
/* 18 */ _CFFI_OP(_CFFI_OP_POINTER, 40), // float const *
/* 19 */ _CFFI_OP(_CFFI_OP_NOOP, 18),
/* 20 */ _CFFI_OP(_CFFI_OP_NOOP, 18),
/* 21 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 22 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 23 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 24 */ _CFFI_OP(_CFFI_OP_FUNCTION, 55), // void()(float _Complex *, float _Complex const *, float _Complex const *, float const *, int const *, uint8_t const *)
/* 25 */ _CFFI_OP(_CFFI_OP_POINTER, 39), // float _Complex *
/* 26 */ _CFFI_OP(_CFFI_OP_POINTER, 39), // float _Complex const *
/* 27 */ _CFFI_OP(_CFFI_OP_NOOP, 26),
/* 28 */ _CFFI_OP(_CFFI_OP_NOOP, 18),
/* 29 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 30 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 31 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 32 */ _CFFI_OP(_CFFI_OP_POINTER, 33), // _Bool const *
/* 33 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1), // _Bool
/* 34 */ _CFFI_OP(_CFFI_OP_POINTER, 35), // char const * *
/* 35 */ _CFFI_OP(_CFFI_OP_POINTER, 36), // char const *
/* 36 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
/* 37 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 49), // double _Complex
/* 38 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14), // double
/* 39 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 48), // float _Complex
/* 40 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 13), // float
/* 41 */ _CFFI_OP(_CFFI_OP_POINTER, 42), // int *
/* 42 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/* 43 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // ufcx_form
/* 44 */ _CFFI_OP(_CFFI_OP_POINTER, 45), // ufcx_integral * *
/* 45 */ _CFFI_OP(_CFFI_OP_POINTER, 46), // ufcx_integral *
/* 46 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 1), // ufcx_integral
/* 47 */ _CFFI_OP(_CFFI_OP_ENUM, 0), // ufcx_integral_type
/* 48 */ _CFFI_OP(_CFFI_OP_POINTER, 49), // uint64_t *
/* 49 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 24), // uint64_t
/* 50 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 18), // uint8_t
/* 51 */ _CFFI_OP(_CFFI_OP_POINTER, 0), // void(*)(double *, double const *, double const *, double const *, int const *, uint8_t const *)
/* 52 */ _CFFI_OP(_CFFI_OP_POINTER, 8), // void(*)(double _Complex *, double _Complex const *, double _Complex const *, double const *, int const *, uint8_t const *)
/* 53 */ _CFFI_OP(_CFFI_OP_POINTER, 16), // void(*)(float *, float const *, float const *, float const *, int const *, uint8_t const *)
/* 54 */ _CFFI_OP(_CFFI_OP_POINTER, 24), // void(*)(float _Complex *, float _Complex const *, float _Complex const *, float const *, int const *, uint8_t const *)
/* 55 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static int _cffi_const_cell(unsigned long long *o)
{
  int n = (cell) <= 0;
  *o = (unsigned long long)((cell) | 0);  /* check that cell is an integer */
  return n;
}

static int _cffi_const_exterior_facet(unsigned long long *o)
{
  int n = (exterior_facet) <= 0;
  *o = (unsigned long long)((exterior_facet) | 0);  /* check that exterior_facet is an integer */
  return n;
}

static int _cffi_const_interior_facet(unsigned long long *o)
{
  int n = (interior_facet) <= 0;
  *o = (unsigned long long)((interior_facet) | 0);  /* check that interior_facet is an integer */
  return n;
}

_CFFI_UNUSED_FN
static void _cffi_checkfld__ufcx_form(ufcx_form *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { char const * *tmp = &p->signature; (void)tmp; }
  (void)((p->rank) | 0);  /* check that 'ufcx_form.rank' is an integer */
  (void)((p->num_coefficients) | 0);  /* check that 'ufcx_form.num_coefficients' is an integer */
  (void)((p->num_constants) | 0);  /* check that 'ufcx_form.num_constants' is an integer */
  { int * *tmp = &p->original_coefficient_positions; (void)tmp; }
  { char const * * *tmp = &p->coefficient_name_map; (void)tmp; }
  { char const * * *tmp = &p->constant_name_map; (void)tmp; }
  { uint64_t * *tmp = &p->finite_element_hashes; (void)tmp; }
  { ufcx_integral * * *tmp = &p->form_integrals; (void)tmp; }
  { int * *tmp = &p->form_integral_ids; (void)tmp; }
  { int * *tmp = &p->form_integral_offsets; (void)tmp; }
}
struct _cffi_align__ufcx_form { char x; ufcx_form y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__ufcx_integral(ufcx_integral *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { _Bool const * *tmp = &p->enabled_coefficients; (void)tmp; }
  { void(* *tmp)(float *, float const *, float const *, float const *, int const *, uint8_t const *) = &p->tabulate_tensor_float32; (void)tmp; }
  { void(* *tmp)(double *, double const *, double const *, double const *, int const *, uint8_t const *) = &p->tabulate_tensor_float64; (void)tmp; }
  { void(* *tmp)(float _Complex *, float _Complex const *, float _Complex const *, float const *, int const *, uint8_t const *) = &p->tabulate_tensor_complex64; (void)tmp; }
  { void(* *tmp)(double _Complex *, double _Complex const *, double _Complex const *, double const *, int const *, uint8_t const *) = &p->tabulate_tensor_complex128; (void)tmp; }
  (void)((p->needs_facet_permutations) | 0);  /* check that 'ufcx_integral.needs_facet_permutations' is an integer */
  (void)((p->coordinate_element_hash) | 0);  /* check that 'ufcx_integral.coordinate_element_hash' is an integer */
}
struct _cffi_align__ufcx_integral { char x; ufcx_integral y; };

static ufcx_form *_cffi_var_form_22e951a9bc4b20597ab54228324b1cdd275d43cb(void)
{
  return &(form_22e951a9bc4b20597ab54228324b1cdd275d43cb);
}

static const struct _cffi_global_s _cffi_globals[] = {
  { "cell", (void *)_cffi_const_cell, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "exterior_facet", (void *)_cffi_const_exterior_facet, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "form_22e951a9bc4b20597ab54228324b1cdd275d43cb", (void *)_cffi_var_form_22e951a9bc4b20597ab54228324b1cdd275d43cb, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 43), (void *)0 },
  { "interior_facet", (void *)_cffi_const_interior_facet, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
};

static const struct _cffi_field_s _cffi_fields[] = {
  { "signature", offsetof(ufcx_form, signature),
                 sizeof(((ufcx_form *)0)->signature),
                 _CFFI_OP(_CFFI_OP_NOOP, 35) },
  { "rank", offsetof(ufcx_form, rank),
            sizeof(((ufcx_form *)0)->rank),
            _CFFI_OP(_CFFI_OP_NOOP, 42) },
  { "num_coefficients", offsetof(ufcx_form, num_coefficients),
                        sizeof(((ufcx_form *)0)->num_coefficients),
                        _CFFI_OP(_CFFI_OP_NOOP, 42) },
  { "num_constants", offsetof(ufcx_form, num_constants),
                     sizeof(((ufcx_form *)0)->num_constants),
                     _CFFI_OP(_CFFI_OP_NOOP, 42) },
  { "original_coefficient_positions", offsetof(ufcx_form, original_coefficient_positions),
                                      sizeof(((ufcx_form *)0)->original_coefficient_positions),
                                      _CFFI_OP(_CFFI_OP_NOOP, 41) },
  { "coefficient_name_map", offsetof(ufcx_form, coefficient_name_map),
                            sizeof(((ufcx_form *)0)->coefficient_name_map),
                            _CFFI_OP(_CFFI_OP_NOOP, 34) },
  { "constant_name_map", offsetof(ufcx_form, constant_name_map),
                         sizeof(((ufcx_form *)0)->constant_name_map),
                         _CFFI_OP(_CFFI_OP_NOOP, 34) },
  { "finite_element_hashes", offsetof(ufcx_form, finite_element_hashes),
                             sizeof(((ufcx_form *)0)->finite_element_hashes),
                             _CFFI_OP(_CFFI_OP_NOOP, 48) },
  { "form_integrals", offsetof(ufcx_form, form_integrals),
                      sizeof(((ufcx_form *)0)->form_integrals),
                      _CFFI_OP(_CFFI_OP_NOOP, 44) },
  { "form_integral_ids", offsetof(ufcx_form, form_integral_ids),
                         sizeof(((ufcx_form *)0)->form_integral_ids),
                         _CFFI_OP(_CFFI_OP_NOOP, 41) },
  { "form_integral_offsets", offsetof(ufcx_form, form_integral_offsets),
                             sizeof(((ufcx_form *)0)->form_integral_offsets),
                             _CFFI_OP(_CFFI_OP_NOOP, 41) },
  { "enabled_coefficients", offsetof(ufcx_integral, enabled_coefficients),
                            sizeof(((ufcx_integral *)0)->enabled_coefficients),
                            _CFFI_OP(_CFFI_OP_NOOP, 32) },
  { "tabulate_tensor_float32", offsetof(ufcx_integral, tabulate_tensor_float32),
                               sizeof(((ufcx_integral *)0)->tabulate_tensor_float32),
                               _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "tabulate_tensor_float64", offsetof(ufcx_integral, tabulate_tensor_float64),
                               sizeof(((ufcx_integral *)0)->tabulate_tensor_float64),
                               _CFFI_OP(_CFFI_OP_NOOP, 51) },
  { "tabulate_tensor_complex64", offsetof(ufcx_integral, tabulate_tensor_complex64),
                                 sizeof(((ufcx_integral *)0)->tabulate_tensor_complex64),
                                 _CFFI_OP(_CFFI_OP_NOOP, 54) },
  { "tabulate_tensor_complex128", offsetof(ufcx_integral, tabulate_tensor_complex128),
                                  sizeof(((ufcx_integral *)0)->tabulate_tensor_complex128),
                                  _CFFI_OP(_CFFI_OP_NOOP, 52) },
  { "needs_facet_permutations", offsetof(ufcx_integral, needs_facet_permutations),
                                sizeof(((ufcx_integral *)0)->needs_facet_permutations),
                                _CFFI_OP(_CFFI_OP_NOOP, 33) },
  { "coordinate_element_hash", offsetof(ufcx_integral, coordinate_element_hash),
                               sizeof(((ufcx_integral *)0)->coordinate_element_hash),
                               _CFFI_OP(_CFFI_OP_NOOP, 49) },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "ufcx_form", 43, _CFFI_F_CHECK_FIELDS,
    sizeof(ufcx_form), offsetof(struct _cffi_align__ufcx_form, y), 0, 11 },
  { "ufcx_integral", 46, _CFFI_F_CHECK_FIELDS,
    sizeof(ufcx_integral), offsetof(struct _cffi_align__ufcx_integral, y), 11, 7 },
};

static const struct _cffi_enum_s _cffi_enums[] = {
  { "$ufcx_integral_type", 47, _cffi_prim_int(sizeof(ufcx_integral_type), ((ufcx_integral_type)-1) <= 0),
    "cell,exterior_facet,interior_facet" },
};

static const struct _cffi_typename_s _cffi_typenames[] = {
  { "ufcx_form", 43 },
  { "ufcx_integral", 46 },
  { "ufcx_integral_type", 47 },
  { "ufcx_tabulate_tensor_complex128", 8 },
  { "ufcx_tabulate_tensor_complex64", 24 },
  { "ufcx_tabulate_tensor_float32", 16 },
  { "ufcx_tabulate_tensor_float64", 0 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  _cffi_fields,
  _cffi_struct_unions,
  _cffi_enums,
  _cffi_typenames,
  4,  /* num_globals */
  2,  /* num_struct_unions */
  1,  /* num_enums */
  7,  /* num_typenames */
  NULL,  /* no includes */
  56,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_libffcx_forms_006c7f09c00364dbb57168308ad49c342d0e249f(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit_libffcx_forms_006c7f09c00364dbb57168308ad49c342d0e249f(void) { return NULL; }
#  else
     initlibffcx_forms_006c7f09c00364dbb57168308ad49c342d0e249f(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit_libffcx_forms_006c7f09c00364dbb57168308ad49c342d0e249f(void)
{
  return _cffi_init("libffcx_forms_006c7f09c00364dbb57168308ad49c342d0e249f", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
initlibffcx_forms_006c7f09c00364dbb57168308ad49c342d0e249f(void)
{
  _cffi_init("libffcx_forms_006c7f09c00364dbb57168308ad49c342d0e249f", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
