#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/


// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.9.0.
//
// This code was generated with the following options:
//
//  {'epsilon': 1e-14,
//   'scalar_type': <class 'numpy.float64'>,
//   'sum_factorization': False,
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'verbosity': 30}

#include <math.h>
#include <stdalign.h>
#include <stdlib.h>
#include <string.h>
#include <ufcx.h>



// Code for integral integral_bb392318a7cdd42062be8c861fa77bdd276a68ca

void tabulate_tensor_integral_bb392318a7cdd42062be8c861fa77bdd276a68ca(double* restrict A,
                                    const double* restrict w,
                                    const double* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation)
{
// Quadrature rules
static const double weights_421[1] = {0.1666666666666667};
// Precomputed values of basis functions and precomputations
// FE* dimensions: [permutation][entities][points][dofs]
static const double FE1_C1_D010_Q421[1][1][1][4] = {{{{-1.0, 0.0, 1.0, 0.0}}}};
static const double FE1_C2_D001_Q421[1][1][1][4] = {{{{-1.0, 0.0, 0.0, 1.0}}}};
static const double FE3_C0_D100_Q421[1][1][1][4] = {{{{-1.0, 1.0, 0.0, 0.0}}}};
// ------------------------ 
// Section: Jacobian
// Inputs: FE3_C0_D100_Q421, FE1_C2_D001_Q421, coordinate_dofs, FE1_C1_D010_Q421
// Outputs: J_c1, J_c6, J_c5, J_c8, J_c2, J_c3, J_c4, J_c0, J_c7
double J_c4 = 0.0;
double J_c8 = 0.0;
double J_c5 = 0.0;
double J_c7 = 0.0;
double J_c0 = 0.0;
double J_c3 = 0.0;
double J_c6 = 0.0;
double J_c1 = 0.0;
double J_c2 = 0.0;
{
  for (int ic = 0; ic < 4; ++ic)
  {
    J_c4 += coordinate_dofs[(ic) * 3 + 1] * FE1_C1_D010_Q421[0][0][0][ic];
    J_c8 += coordinate_dofs[(ic) * 3 + 2] * FE1_C2_D001_Q421[0][0][0][ic];
    J_c5 += coordinate_dofs[(ic) * 3 + 1] * FE1_C2_D001_Q421[0][0][0][ic];
    J_c7 += coordinate_dofs[(ic) * 3 + 2] * FE1_C1_D010_Q421[0][0][0][ic];
    J_c0 += coordinate_dofs[(ic) * 3] * FE3_C0_D100_Q421[0][0][0][ic];
    J_c3 += coordinate_dofs[(ic) * 3 + 1] * FE3_C0_D100_Q421[0][0][0][ic];
    J_c6 += coordinate_dofs[(ic) * 3 + 2] * FE3_C0_D100_Q421[0][0][0][ic];
    J_c1 += coordinate_dofs[(ic) * 3] * FE1_C1_D010_Q421[0][0][0][ic];
    J_c2 += coordinate_dofs[(ic) * 3] * FE1_C2_D001_Q421[0][0][0][ic];
  }
}
// ------------------------ 
double sp_421_0 = J_c4 * J_c8;
double sp_421_1 = J_c5 * J_c7;
double sp_421_2 = -sp_421_1;
double sp_421_3 = sp_421_0 + sp_421_2;
double sp_421_4 = J_c0 * sp_421_3;
double sp_421_5 = J_c3 * J_c8;
double sp_421_6 = J_c5 * J_c6;
double sp_421_7 = -sp_421_6;
double sp_421_8 = sp_421_5 + sp_421_7;
double sp_421_9 = -J_c1;
double sp_421_10 = sp_421_8 * sp_421_9;
double sp_421_11 = sp_421_4 + sp_421_10;
double sp_421_12 = J_c3 * J_c7;
double sp_421_13 = J_c4 * J_c6;
double sp_421_14 = -sp_421_13;
double sp_421_15 = sp_421_12 + sp_421_14;
double sp_421_16 = J_c2 * sp_421_15;
double sp_421_17 = sp_421_11 + sp_421_16;
double sp_421_18 = sp_421_3 / sp_421_17;
double sp_421_19 = -J_c8;
double sp_421_20 = J_c3 * sp_421_19;
double sp_421_21 = sp_421_6 + sp_421_20;
double sp_421_22 = sp_421_21 / sp_421_17;
double sp_421_23 = sp_421_15 / sp_421_17;
double sp_421_24 = sp_421_18 + sp_421_18;
double sp_421_25 = sp_421_22 + sp_421_22;
double sp_421_26 = sp_421_23 + sp_421_23;
double sp_421_27 = sp_421_24 / 2;
double sp_421_28 = sp_421_25 / 2;
double sp_421_29 = sp_421_26 / 2;
double sp_421_30 = J_c2 * J_c7;
double sp_421_31 = J_c8 * sp_421_9;
double sp_421_32 = sp_421_30 + sp_421_31;
double sp_421_33 = sp_421_32 / sp_421_17;
double sp_421_34 = J_c0 * J_c8;
double sp_421_35 = -J_c2;
double sp_421_36 = J_c6 * sp_421_35;
double sp_421_37 = sp_421_34 + sp_421_36;
double sp_421_38 = sp_421_37 / sp_421_17;
double sp_421_39 = J_c1 * J_c6;
double sp_421_40 = J_c0 * J_c7;
double sp_421_41 = -sp_421_40;
double sp_421_42 = sp_421_39 + sp_421_41;
double sp_421_43 = sp_421_42 / sp_421_17;
double sp_421_44 = sp_421_33 + sp_421_33;
double sp_421_45 = sp_421_38 + sp_421_38;
double sp_421_46 = sp_421_43 + sp_421_43;
double sp_421_47 = sp_421_44 / 2;
double sp_421_48 = sp_421_45 / 2;
double sp_421_49 = sp_421_46 / 2;
double sp_421_50 = J_c1 * J_c5;
double sp_421_51 = J_c2 * J_c4;
double sp_421_52 = -sp_421_51;
double sp_421_53 = sp_421_50 + sp_421_52;
double sp_421_54 = sp_421_53 / sp_421_17;
double sp_421_55 = J_c2 * J_c3;
double sp_421_56 = J_c0 * J_c5;
double sp_421_57 = -sp_421_56;
double sp_421_58 = sp_421_55 + sp_421_57;
double sp_421_59 = sp_421_58 / sp_421_17;
double sp_421_60 = J_c0 * J_c4;
double sp_421_61 = J_c1 * J_c3;
double sp_421_62 = -sp_421_61;
double sp_421_63 = sp_421_60 + sp_421_62;
double sp_421_64 = sp_421_63 / sp_421_17;
double sp_421_65 = sp_421_54 + sp_421_54;
double sp_421_66 = sp_421_59 + sp_421_59;
double sp_421_67 = sp_421_64 + sp_421_64;
double sp_421_68 = sp_421_65 / 2;
double sp_421_69 = sp_421_66 / 2;
double sp_421_70 = sp_421_67 / 2;
double sp_421_71 = 10346968338.27688 * sp_421_27;
double sp_421_72 = 10346968338.27688 * sp_421_28;
double sp_421_73 = 10346968338.27688 * sp_421_29;
double sp_421_74 = 10346968338.27688 * sp_421_47;
double sp_421_75 = 10346968338.27688 * sp_421_48;
double sp_421_76 = 10346968338.27688 * sp_421_49;
double sp_421_77 = 10346968338.27688 * sp_421_68;
double sp_421_78 = 10346968338.27688 * sp_421_69;
double sp_421_79 = 10346968338.27688 * sp_421_70;
double sp_421_80 = 140977443609.0226 * sp_421_27;
double sp_421_81 = 140977443609.0226 * sp_421_28;
double sp_421_82 = 140977443609.0226 * sp_421_29;
double sp_421_83 = sp_421_71 + sp_421_80;
double sp_421_84 = sp_421_72 + sp_421_81;
double sp_421_85 = sp_421_73 + sp_421_82;
double sp_421_86 = sp_421_83 * sp_421_27;
double sp_421_87 = sp_421_83 * sp_421_28;
double sp_421_88 = sp_421_83 * sp_421_29;
double sp_421_89 = sp_421_84 * sp_421_27;
double sp_421_90 = sp_421_84 * sp_421_28;
double sp_421_91 = sp_421_84 * sp_421_29;
double sp_421_92 = sp_421_85 * sp_421_27;
double sp_421_93 = sp_421_85 * sp_421_28;
double sp_421_94 = sp_421_85 * sp_421_29;
double sp_421_95 = sp_421_74 * sp_421_27;
double sp_421_96 = sp_421_74 * sp_421_28;
double sp_421_97 = sp_421_74 * sp_421_29;
double sp_421_98 = sp_421_75 * sp_421_27;
double sp_421_99 = sp_421_75 * sp_421_28;
double sp_421_100 = sp_421_75 * sp_421_29;
double sp_421_101 = sp_421_76 * sp_421_27;
double sp_421_102 = sp_421_76 * sp_421_28;
double sp_421_103 = sp_421_76 * sp_421_29;
double sp_421_104 = sp_421_77 * sp_421_27;
double sp_421_105 = sp_421_77 * sp_421_28;
double sp_421_106 = sp_421_77 * sp_421_29;
double sp_421_107 = sp_421_78 * sp_421_27;
double sp_421_108 = sp_421_78 * sp_421_28;
double sp_421_109 = sp_421_78 * sp_421_29;
double sp_421_110 = sp_421_79 * sp_421_27;
double sp_421_111 = sp_421_79 * sp_421_28;
double sp_421_112 = sp_421_79 * sp_421_29;
double sp_421_113 = sp_421_33 / 2;
double sp_421_114 = sp_421_38 / 2;
double sp_421_115 = sp_421_43 / 2;
double sp_421_116 = sp_421_18 / 2;
double sp_421_117 = sp_421_22 / 2;
double sp_421_118 = sp_421_23 / 2;
double sp_421_119 = 140977443609.0226 * sp_421_113;
double sp_421_120 = 140977443609.0226 * sp_421_114;
double sp_421_121 = 140977443609.0226 * sp_421_115;
double sp_421_122 = 140977443609.0226 * sp_421_116;
double sp_421_123 = 140977443609.0226 * sp_421_117;
double sp_421_124 = 140977443609.0226 * sp_421_118;
double sp_421_125 = sp_421_119 * sp_421_113;
double sp_421_126 = sp_421_119 * sp_421_114;
double sp_421_127 = sp_421_119 * sp_421_115;
double sp_421_128 = sp_421_119 * sp_421_116;
double sp_421_129 = sp_421_119 * sp_421_117;
double sp_421_130 = sp_421_119 * sp_421_118;
double sp_421_131 = sp_421_120 * sp_421_113;
double sp_421_132 = sp_421_120 * sp_421_114;
double sp_421_133 = sp_421_120 * sp_421_115;
double sp_421_134 = sp_421_120 * sp_421_116;
double sp_421_135 = sp_421_120 * sp_421_117;
double sp_421_136 = sp_421_120 * sp_421_118;
double sp_421_137 = sp_421_121 * sp_421_113;
double sp_421_138 = sp_421_121 * sp_421_114;
double sp_421_139 = sp_421_121 * sp_421_115;
double sp_421_140 = sp_421_121 * sp_421_116;
double sp_421_141 = sp_421_121 * sp_421_117;
double sp_421_142 = sp_421_121 * sp_421_118;
double sp_421_143 = sp_421_122 * sp_421_113;
double sp_421_144 = sp_421_122 * sp_421_114;
double sp_421_145 = sp_421_122 * sp_421_115;
double sp_421_146 = sp_421_122 * sp_421_116;
double sp_421_147 = sp_421_122 * sp_421_117;
double sp_421_148 = sp_421_122 * sp_421_118;
double sp_421_149 = sp_421_123 * sp_421_113;
double sp_421_150 = sp_421_123 * sp_421_114;
double sp_421_151 = sp_421_123 * sp_421_115;
double sp_421_152 = sp_421_123 * sp_421_116;
double sp_421_153 = sp_421_123 * sp_421_117;
double sp_421_154 = sp_421_123 * sp_421_118;
double sp_421_155 = sp_421_124 * sp_421_113;
double sp_421_156 = sp_421_124 * sp_421_114;
double sp_421_157 = sp_421_124 * sp_421_115;
double sp_421_158 = sp_421_124 * sp_421_116;
double sp_421_159 = sp_421_124 * sp_421_117;
double sp_421_160 = sp_421_124 * sp_421_118;
double sp_421_161 = sp_421_86 + sp_421_125;
double sp_421_162 = sp_421_87 + sp_421_126;
double sp_421_163 = sp_421_88 + sp_421_127;
double sp_421_164 = sp_421_89 + sp_421_131;
double sp_421_165 = sp_421_90 + sp_421_132;
double sp_421_166 = sp_421_91 + sp_421_133;
double sp_421_167 = sp_421_92 + sp_421_137;
double sp_421_168 = sp_421_93 + sp_421_138;
double sp_421_169 = sp_421_94 + sp_421_139;
double sp_421_170 = sp_421_95 + sp_421_143;
double sp_421_171 = sp_421_96 + sp_421_144;
double sp_421_172 = sp_421_97 + sp_421_145;
double sp_421_173 = sp_421_98 + sp_421_149;
double sp_421_174 = sp_421_99 + sp_421_150;
double sp_421_175 = sp_421_100 + sp_421_151;
double sp_421_176 = sp_421_101 + sp_421_155;
double sp_421_177 = sp_421_102 + sp_421_156;
double sp_421_178 = sp_421_103 + sp_421_157;
double sp_421_179 = sp_421_54 / 2;
double sp_421_180 = sp_421_59 / 2;
double sp_421_181 = sp_421_64 / 2;
double sp_421_182 = 140977443609.0226 * sp_421_179;
double sp_421_183 = 140977443609.0226 * sp_421_180;
double sp_421_184 = 140977443609.0226 * sp_421_181;
double sp_421_185 = sp_421_182 * sp_421_179;
double sp_421_186 = sp_421_182 * sp_421_180;
double sp_421_187 = sp_421_182 * sp_421_181;
double sp_421_188 = sp_421_182 * sp_421_116;
double sp_421_189 = sp_421_182 * sp_421_117;
double sp_421_190 = sp_421_182 * sp_421_118;
double sp_421_191 = sp_421_183 * sp_421_179;
double sp_421_192 = sp_421_183 * sp_421_180;
double sp_421_193 = sp_421_183 * sp_421_181;
double sp_421_194 = sp_421_183 * sp_421_116;
double sp_421_195 = sp_421_183 * sp_421_117;
double sp_421_196 = sp_421_183 * sp_421_118;
double sp_421_197 = sp_421_184 * sp_421_179;
double sp_421_198 = sp_421_184 * sp_421_180;
double sp_421_199 = sp_421_184 * sp_421_181;
double sp_421_200 = sp_421_184 * sp_421_116;
double sp_421_201 = sp_421_184 * sp_421_117;
double sp_421_202 = sp_421_184 * sp_421_118;
double sp_421_203 = sp_421_122 * sp_421_179;
double sp_421_204 = sp_421_122 * sp_421_180;
double sp_421_205 = sp_421_122 * sp_421_181;
double sp_421_206 = sp_421_123 * sp_421_179;
double sp_421_207 = sp_421_123 * sp_421_180;
double sp_421_208 = sp_421_123 * sp_421_181;
double sp_421_209 = sp_421_124 * sp_421_179;
double sp_421_210 = sp_421_124 * sp_421_180;
double sp_421_211 = sp_421_124 * sp_421_181;
double sp_421_212 = sp_421_161 + sp_421_185;
double sp_421_213 = sp_421_162 + sp_421_186;
double sp_421_214 = sp_421_163 + sp_421_187;
double sp_421_215 = sp_421_164 + sp_421_191;
double sp_421_216 = sp_421_165 + sp_421_192;
double sp_421_217 = sp_421_166 + sp_421_193;
double sp_421_218 = sp_421_167 + sp_421_197;
double sp_421_219 = sp_421_168 + sp_421_198;
double sp_421_220 = sp_421_169 + sp_421_199;
double sp_421_221 = sp_421_104 + sp_421_203;
double sp_421_222 = sp_421_105 + sp_421_204;
double sp_421_223 = sp_421_106 + sp_421_205;
double sp_421_224 = sp_421_107 + sp_421_206;
double sp_421_225 = sp_421_108 + sp_421_207;
double sp_421_226 = sp_421_109 + sp_421_208;
double sp_421_227 = sp_421_110 + sp_421_209;
double sp_421_228 = sp_421_111 + sp_421_210;
double sp_421_229 = sp_421_112 + sp_421_211;
double sp_421_230 = 140977443609.0226 * sp_421_47;
double sp_421_231 = 140977443609.0226 * sp_421_48;
double sp_421_232 = 140977443609.0226 * sp_421_49;
double sp_421_233 = sp_421_74 + sp_421_230;
double sp_421_234 = sp_421_75 + sp_421_231;
double sp_421_235 = sp_421_76 + sp_421_232;
double sp_421_236 = sp_421_71 * sp_421_47;
double sp_421_237 = sp_421_71 * sp_421_48;
double sp_421_238 = sp_421_71 * sp_421_49;
double sp_421_239 = sp_421_72 * sp_421_47;
double sp_421_240 = sp_421_72 * sp_421_48;
double sp_421_241 = sp_421_72 * sp_421_49;
double sp_421_242 = sp_421_73 * sp_421_47;
double sp_421_243 = sp_421_73 * sp_421_48;
double sp_421_244 = sp_421_73 * sp_421_49;
double sp_421_245 = sp_421_233 * sp_421_47;
double sp_421_246 = sp_421_233 * sp_421_48;
double sp_421_247 = sp_421_233 * sp_421_49;
double sp_421_248 = sp_421_234 * sp_421_47;
double sp_421_249 = sp_421_234 * sp_421_48;
double sp_421_250 = sp_421_234 * sp_421_49;
double sp_421_251 = sp_421_235 * sp_421_47;
double sp_421_252 = sp_421_235 * sp_421_48;
double sp_421_253 = sp_421_235 * sp_421_49;
double sp_421_254 = sp_421_77 * sp_421_47;
double sp_421_255 = sp_421_77 * sp_421_48;
double sp_421_256 = sp_421_77 * sp_421_49;
double sp_421_257 = sp_421_78 * sp_421_47;
double sp_421_258 = sp_421_78 * sp_421_48;
double sp_421_259 = sp_421_78 * sp_421_49;
double sp_421_260 = sp_421_79 * sp_421_47;
double sp_421_261 = sp_421_79 * sp_421_48;
double sp_421_262 = sp_421_79 * sp_421_49;
double sp_421_263 = sp_421_236 + sp_421_128;
double sp_421_264 = sp_421_237 + sp_421_129;
double sp_421_265 = sp_421_238 + sp_421_130;
double sp_421_266 = sp_421_239 + sp_421_134;
double sp_421_267 = sp_421_240 + sp_421_135;
double sp_421_268 = sp_421_241 + sp_421_136;
double sp_421_269 = sp_421_242 + sp_421_140;
double sp_421_270 = sp_421_243 + sp_421_141;
double sp_421_271 = sp_421_244 + sp_421_142;
double sp_421_272 = sp_421_245 + sp_421_146;
double sp_421_273 = sp_421_246 + sp_421_147;
double sp_421_274 = sp_421_247 + sp_421_148;
double sp_421_275 = sp_421_248 + sp_421_152;
double sp_421_276 = sp_421_249 + sp_421_153;
double sp_421_277 = sp_421_250 + sp_421_154;
double sp_421_278 = sp_421_251 + sp_421_158;
double sp_421_279 = sp_421_252 + sp_421_159;
double sp_421_280 = sp_421_253 + sp_421_160;
double sp_421_281 = sp_421_182 * sp_421_113;
double sp_421_282 = sp_421_182 * sp_421_114;
double sp_421_283 = sp_421_182 * sp_421_115;
double sp_421_284 = sp_421_183 * sp_421_113;
double sp_421_285 = sp_421_183 * sp_421_114;
double sp_421_286 = sp_421_183 * sp_421_115;
double sp_421_287 = sp_421_184 * sp_421_113;
double sp_421_288 = sp_421_184 * sp_421_114;
double sp_421_289 = sp_421_184 * sp_421_115;
double sp_421_290 = sp_421_119 * sp_421_179;
double sp_421_291 = sp_421_119 * sp_421_180;
double sp_421_292 = sp_421_119 * sp_421_181;
double sp_421_293 = sp_421_120 * sp_421_179;
double sp_421_294 = sp_421_120 * sp_421_180;
double sp_421_295 = sp_421_120 * sp_421_181;
double sp_421_296 = sp_421_121 * sp_421_179;
double sp_421_297 = sp_421_121 * sp_421_180;
double sp_421_298 = sp_421_121 * sp_421_181;
double sp_421_299 = sp_421_272 + sp_421_185;
double sp_421_300 = sp_421_273 + sp_421_186;
double sp_421_301 = sp_421_274 + sp_421_187;
double sp_421_302 = sp_421_275 + sp_421_191;
double sp_421_303 = sp_421_276 + sp_421_192;
double sp_421_304 = sp_421_277 + sp_421_193;
double sp_421_305 = sp_421_278 + sp_421_197;
double sp_421_306 = sp_421_279 + sp_421_198;
double sp_421_307 = sp_421_280 + sp_421_199;
double sp_421_308 = sp_421_254 + sp_421_290;
double sp_421_309 = sp_421_255 + sp_421_291;
double sp_421_310 = sp_421_256 + sp_421_292;
double sp_421_311 = sp_421_257 + sp_421_293;
double sp_421_312 = sp_421_258 + sp_421_294;
double sp_421_313 = sp_421_259 + sp_421_295;
double sp_421_314 = sp_421_260 + sp_421_296;
double sp_421_315 = sp_421_261 + sp_421_297;
double sp_421_316 = sp_421_262 + sp_421_298;
double sp_421_317 = sp_421_212 + sp_421_125;
double sp_421_318 = sp_421_213 + sp_421_126;
double sp_421_319 = sp_421_214 + sp_421_127;
double sp_421_320 = sp_421_263 + sp_421_128;
double sp_421_321 = sp_421_264 + sp_421_129;
double sp_421_322 = sp_421_265 + sp_421_130;
double sp_421_323 = sp_421_215 + sp_421_131;
double sp_421_324 = sp_421_216 + sp_421_132;
double sp_421_325 = sp_421_217 + sp_421_133;
double sp_421_326 = sp_421_266 + sp_421_134;
double sp_421_327 = sp_421_267 + sp_421_135;
double sp_421_328 = sp_421_268 + sp_421_136;
double sp_421_329 = sp_421_218 + sp_421_137;
double sp_421_330 = sp_421_219 + sp_421_138;
double sp_421_331 = sp_421_220 + sp_421_139;
double sp_421_332 = sp_421_269 + sp_421_140;
double sp_421_333 = sp_421_270 + sp_421_141;
double sp_421_334 = sp_421_271 + sp_421_142;
double sp_421_335 = sp_421_170 + sp_421_143;
double sp_421_336 = sp_421_171 + sp_421_144;
double sp_421_337 = sp_421_172 + sp_421_145;
double sp_421_338 = sp_421_299 + sp_421_146;
double sp_421_339 = sp_421_300 + sp_421_147;
double sp_421_340 = sp_421_301 + sp_421_148;
double sp_421_341 = sp_421_173 + sp_421_149;
double sp_421_342 = sp_421_174 + sp_421_150;
double sp_421_343 = sp_421_175 + sp_421_151;
double sp_421_344 = sp_421_302 + sp_421_152;
double sp_421_345 = sp_421_303 + sp_421_153;
double sp_421_346 = sp_421_304 + sp_421_154;
double sp_421_347 = sp_421_176 + sp_421_155;
double sp_421_348 = sp_421_177 + sp_421_156;
double sp_421_349 = sp_421_178 + sp_421_157;
double sp_421_350 = sp_421_305 + sp_421_158;
double sp_421_351 = sp_421_306 + sp_421_159;
double sp_421_352 = sp_421_307 + sp_421_160;
double sp_421_353 = sp_421_125 + sp_421_146;
double sp_421_354 = sp_421_126 + sp_421_147;
double sp_421_355 = sp_421_148 + sp_421_127;
double sp_421_356 = sp_421_131 + sp_421_152;
double sp_421_357 = sp_421_132 + sp_421_153;
double sp_421_358 = sp_421_154 + sp_421_133;
double sp_421_359 = sp_421_137 + sp_421_158;
double sp_421_360 = sp_421_138 + sp_421_159;
double sp_421_361 = sp_421_160 + sp_421_139;
double sp_421_362 = 140977443609.0226 * sp_421_68;
double sp_421_363 = 140977443609.0226 * sp_421_69;
double sp_421_364 = 140977443609.0226 * sp_421_70;
double sp_421_365 = sp_421_77 + sp_421_362;
double sp_421_366 = sp_421_78 + sp_421_363;
double sp_421_367 = sp_421_79 + sp_421_364;
double sp_421_368 = sp_421_71 * sp_421_68;
double sp_421_369 = sp_421_71 * sp_421_69;
double sp_421_370 = sp_421_71 * sp_421_70;
double sp_421_371 = sp_421_72 * sp_421_68;
double sp_421_372 = sp_421_72 * sp_421_69;
double sp_421_373 = sp_421_72 * sp_421_70;
double sp_421_374 = sp_421_73 * sp_421_68;
double sp_421_375 = sp_421_73 * sp_421_69;
double sp_421_376 = sp_421_73 * sp_421_70;
double sp_421_377 = sp_421_74 * sp_421_68;
double sp_421_378 = sp_421_74 * sp_421_69;
double sp_421_379 = sp_421_74 * sp_421_70;
double sp_421_380 = sp_421_75 * sp_421_68;
double sp_421_381 = sp_421_75 * sp_421_69;
double sp_421_382 = sp_421_75 * sp_421_70;
double sp_421_383 = sp_421_76 * sp_421_68;
double sp_421_384 = sp_421_76 * sp_421_69;
double sp_421_385 = sp_421_76 * sp_421_70;
double sp_421_386 = sp_421_365 * sp_421_68;
double sp_421_387 = sp_421_365 * sp_421_69;
double sp_421_388 = sp_421_365 * sp_421_70;
double sp_421_389 = sp_421_366 * sp_421_68;
double sp_421_390 = sp_421_366 * sp_421_69;
double sp_421_391 = sp_421_366 * sp_421_70;
double sp_421_392 = sp_421_367 * sp_421_68;
double sp_421_393 = sp_421_367 * sp_421_69;
double sp_421_394 = sp_421_367 * sp_421_70;
double sp_421_395 = sp_421_368 + sp_421_188;
double sp_421_396 = sp_421_369 + sp_421_189;
double sp_421_397 = sp_421_370 + sp_421_190;
double sp_421_398 = sp_421_371 + sp_421_194;
double sp_421_399 = sp_421_372 + sp_421_195;
double sp_421_400 = sp_421_373 + sp_421_196;
double sp_421_401 = sp_421_374 + sp_421_200;
double sp_421_402 = sp_421_375 + sp_421_201;
double sp_421_403 = sp_421_376 + sp_421_202;
double sp_421_404 = sp_421_377 + sp_421_281;
double sp_421_405 = sp_421_378 + sp_421_282;
double sp_421_406 = sp_421_379 + sp_421_283;
double sp_421_407 = sp_421_380 + sp_421_284;
double sp_421_408 = sp_421_381 + sp_421_285;
double sp_421_409 = sp_421_382 + sp_421_286;
double sp_421_410 = sp_421_383 + sp_421_287;
double sp_421_411 = sp_421_384 + sp_421_288;
double sp_421_412 = sp_421_385 + sp_421_289;
double sp_421_413 = sp_421_353 + sp_421_386;
double sp_421_414 = sp_421_354 + sp_421_387;
double sp_421_415 = sp_421_355 + sp_421_388;
double sp_421_416 = sp_421_356 + sp_421_389;
double sp_421_417 = sp_421_357 + sp_421_390;
double sp_421_418 = sp_421_358 + sp_421_391;
double sp_421_419 = sp_421_359 + sp_421_392;
double sp_421_420 = sp_421_360 + sp_421_393;
double sp_421_421 = sp_421_361 + sp_421_394;
double sp_421_422 = sp_421_317 + sp_421_185;
double sp_421_423 = sp_421_318 + sp_421_186;
double sp_421_424 = sp_421_319 + sp_421_187;
double sp_421_425 = sp_421_395 + sp_421_188;
double sp_421_426 = sp_421_396 + sp_421_189;
double sp_421_427 = sp_421_397 + sp_421_190;
double sp_421_428 = sp_421_323 + sp_421_191;
double sp_421_429 = sp_421_324 + sp_421_192;
double sp_421_430 = sp_421_325 + sp_421_193;
double sp_421_431 = sp_421_398 + sp_421_194;
double sp_421_432 = sp_421_399 + sp_421_195;
double sp_421_433 = sp_421_400 + sp_421_196;
double sp_421_434 = sp_421_329 + sp_421_197;
double sp_421_435 = sp_421_330 + sp_421_198;
double sp_421_436 = sp_421_331 + sp_421_199;
double sp_421_437 = sp_421_401 + sp_421_200;
double sp_421_438 = sp_421_402 + sp_421_201;
double sp_421_439 = sp_421_403 + sp_421_202;
double sp_421_440 = sp_421_338 + sp_421_185;
double sp_421_441 = sp_421_339 + sp_421_186;
double sp_421_442 = sp_421_340 + sp_421_187;
double sp_421_443 = sp_421_404 + sp_421_281;
double sp_421_444 = sp_421_405 + sp_421_282;
double sp_421_445 = sp_421_406 + sp_421_283;
double sp_421_446 = sp_421_344 + sp_421_191;
double sp_421_447 = sp_421_345 + sp_421_192;
double sp_421_448 = sp_421_346 + sp_421_193;
double sp_421_449 = sp_421_407 + sp_421_284;
double sp_421_450 = sp_421_408 + sp_421_285;
double sp_421_451 = sp_421_409 + sp_421_286;
double sp_421_452 = sp_421_350 + sp_421_197;
double sp_421_453 = sp_421_351 + sp_421_198;
double sp_421_454 = sp_421_352 + sp_421_199;
double sp_421_455 = sp_421_410 + sp_421_287;
double sp_421_456 = sp_421_411 + sp_421_288;
double sp_421_457 = sp_421_412 + sp_421_289;
double sp_421_458 = sp_421_221 + sp_421_203;
double sp_421_459 = sp_421_222 + sp_421_204;
double sp_421_460 = sp_421_223 + sp_421_205;
double sp_421_461 = sp_421_308 + sp_421_290;
double sp_421_462 = sp_421_309 + sp_421_291;
double sp_421_463 = sp_421_310 + sp_421_292;
double sp_421_464 = sp_421_413 + sp_421_353;
double sp_421_465 = sp_421_414 + sp_421_354;
double sp_421_466 = sp_421_415 + sp_421_355;
double sp_421_467 = sp_421_224 + sp_421_206;
double sp_421_468 = sp_421_225 + sp_421_207;
double sp_421_469 = sp_421_226 + sp_421_208;
double sp_421_470 = sp_421_311 + sp_421_293;
double sp_421_471 = sp_421_312 + sp_421_294;
double sp_421_472 = sp_421_313 + sp_421_295;
double sp_421_473 = sp_421_416 + sp_421_356;
double sp_421_474 = sp_421_417 + sp_421_357;
double sp_421_475 = sp_421_418 + sp_421_358;
double sp_421_476 = sp_421_227 + sp_421_209;
double sp_421_477 = sp_421_228 + sp_421_210;
double sp_421_478 = sp_421_229 + sp_421_211;
double sp_421_479 = sp_421_314 + sp_421_296;
double sp_421_480 = sp_421_315 + sp_421_297;
double sp_421_481 = sp_421_316 + sp_421_298;
double sp_421_482 = sp_421_419 + sp_421_359;
double sp_421_483 = sp_421_420 + sp_421_360;
double sp_421_484 = sp_421_421 + sp_421_361;
double sp_421_485 = fabs(sp_421_17);
double sp_421_486 = sp_421_422 * sp_421_485;
double sp_421_487 = sp_421_423 * sp_421_485;
double sp_421_488 = sp_421_424 * sp_421_485;
double sp_421_489 = sp_421_320 * sp_421_485;
double sp_421_490 = sp_421_321 * sp_421_485;
double sp_421_491 = sp_421_322 * sp_421_485;
double sp_421_492 = sp_421_425 * sp_421_485;
double sp_421_493 = sp_421_426 * sp_421_485;
double sp_421_494 = sp_421_427 * sp_421_485;
double sp_421_495 = sp_421_428 * sp_421_485;
double sp_421_496 = sp_421_429 * sp_421_485;
double sp_421_497 = sp_421_430 * sp_421_485;
double sp_421_498 = sp_421_326 * sp_421_485;
double sp_421_499 = sp_421_327 * sp_421_485;
double sp_421_500 = sp_421_328 * sp_421_485;
double sp_421_501 = sp_421_431 * sp_421_485;
double sp_421_502 = sp_421_432 * sp_421_485;
double sp_421_503 = sp_421_433 * sp_421_485;
double sp_421_504 = sp_421_434 * sp_421_485;
double sp_421_505 = sp_421_435 * sp_421_485;
double sp_421_506 = sp_421_436 * sp_421_485;
double sp_421_507 = sp_421_332 * sp_421_485;
double sp_421_508 = sp_421_333 * sp_421_485;
double sp_421_509 = sp_421_334 * sp_421_485;
double sp_421_510 = sp_421_437 * sp_421_485;
double sp_421_511 = sp_421_438 * sp_421_485;
double sp_421_512 = sp_421_439 * sp_421_485;
double sp_421_513 = sp_421_335 * sp_421_485;
double sp_421_514 = sp_421_336 * sp_421_485;
double sp_421_515 = sp_421_337 * sp_421_485;
double sp_421_516 = sp_421_440 * sp_421_485;
double sp_421_517 = sp_421_441 * sp_421_485;
double sp_421_518 = sp_421_442 * sp_421_485;
double sp_421_519 = sp_421_443 * sp_421_485;
double sp_421_520 = sp_421_444 * sp_421_485;
double sp_421_521 = sp_421_445 * sp_421_485;
double sp_421_522 = sp_421_341 * sp_421_485;
double sp_421_523 = sp_421_342 * sp_421_485;
double sp_421_524 = sp_421_343 * sp_421_485;
double sp_421_525 = sp_421_446 * sp_421_485;
double sp_421_526 = sp_421_447 * sp_421_485;
double sp_421_527 = sp_421_448 * sp_421_485;
double sp_421_528 = sp_421_449 * sp_421_485;
double sp_421_529 = sp_421_450 * sp_421_485;
double sp_421_530 = sp_421_451 * sp_421_485;
double sp_421_531 = sp_421_347 * sp_421_485;
double sp_421_532 = sp_421_348 * sp_421_485;
double sp_421_533 = sp_421_349 * sp_421_485;
double sp_421_534 = sp_421_452 * sp_421_485;
double sp_421_535 = sp_421_453 * sp_421_485;
double sp_421_536 = sp_421_454 * sp_421_485;
double sp_421_537 = sp_421_455 * sp_421_485;
double sp_421_538 = sp_421_456 * sp_421_485;
double sp_421_539 = sp_421_457 * sp_421_485;
double sp_421_540 = sp_421_458 * sp_421_485;
double sp_421_541 = sp_421_459 * sp_421_485;
double sp_421_542 = sp_421_460 * sp_421_485;
double sp_421_543 = sp_421_461 * sp_421_485;
double sp_421_544 = sp_421_462 * sp_421_485;
double sp_421_545 = sp_421_463 * sp_421_485;
double sp_421_546 = sp_421_464 * sp_421_485;
double sp_421_547 = sp_421_465 * sp_421_485;
double sp_421_548 = sp_421_466 * sp_421_485;
double sp_421_549 = sp_421_467 * sp_421_485;
double sp_421_550 = sp_421_468 * sp_421_485;
double sp_421_551 = sp_421_469 * sp_421_485;
double sp_421_552 = sp_421_470 * sp_421_485;
double sp_421_553 = sp_421_471 * sp_421_485;
double sp_421_554 = sp_421_472 * sp_421_485;
double sp_421_555 = sp_421_473 * sp_421_485;
double sp_421_556 = sp_421_474 * sp_421_485;
double sp_421_557 = sp_421_475 * sp_421_485;
double sp_421_558 = sp_421_476 * sp_421_485;
double sp_421_559 = sp_421_477 * sp_421_485;
double sp_421_560 = sp_421_478 * sp_421_485;
double sp_421_561 = sp_421_479 * sp_421_485;
double sp_421_562 = sp_421_480 * sp_421_485;
double sp_421_563 = sp_421_481 * sp_421_485;
double sp_421_564 = sp_421_482 * sp_421_485;
double sp_421_565 = sp_421_483 * sp_421_485;
double sp_421_566 = sp_421_484 * sp_421_485;
for (int iq = 0; iq < 1; ++iq)
{
  // ------------------------ 
  // Section: Intermediates
  // Inputs: 
  // Outputs: fw0, fw1, fw2, fw3, fw4, fw5, fw6, fw7, fw8, fw9, fw10, fw11, fw12, fw13, fw14, fw15, fw16, fw17, fw18, fw19, fw20, fw21, fw22, fw23, fw24, fw25, fw26, fw27, fw28, fw29, fw30, fw31, fw32, fw33, fw34, fw35, fw36, fw37, fw38, fw39, fw40, fw41, fw42, fw43, fw44, fw45, fw46, fw47, fw48, fw49, fw50, fw51, fw52, fw53, fw54, fw55, fw56, fw57, fw58, fw59, fw60, fw61, fw62, fw63, fw64, fw65, fw66, fw67, fw68, fw69, fw70, fw71, fw72, fw73, fw74, fw75, fw76, fw77, fw78, fw79, fw80
  double fw0 = 0;
  double fw1 = 0;
  double fw2 = 0;
  double fw3 = 0;
  double fw4 = 0;
  double fw5 = 0;
  double fw6 = 0;
  double fw7 = 0;
  double fw8 = 0;
  double fw9 = 0;
  double fw10 = 0;
  double fw11 = 0;
  double fw12 = 0;
  double fw13 = 0;
  double fw14 = 0;
  double fw15 = 0;
  double fw16 = 0;
  double fw17 = 0;
  double fw18 = 0;
  double fw19 = 0;
  double fw20 = 0;
  double fw21 = 0;
  double fw22 = 0;
  double fw23 = 0;
  double fw24 = 0;
  double fw25 = 0;
  double fw26 = 0;
  double fw27 = 0;
  double fw28 = 0;
  double fw29 = 0;
  double fw30 = 0;
  double fw31 = 0;
  double fw32 = 0;
  double fw33 = 0;
  double fw34 = 0;
  double fw35 = 0;
  double fw36 = 0;
  double fw37 = 0;
  double fw38 = 0;
  double fw39 = 0;
  double fw40 = 0;
  double fw41 = 0;
  double fw42 = 0;
  double fw43 = 0;
  double fw44 = 0;
  double fw45 = 0;
  double fw46 = 0;
  double fw47 = 0;
  double fw48 = 0;
  double fw49 = 0;
  double fw50 = 0;
  double fw51 = 0;
  double fw52 = 0;
  double fw53 = 0;
  double fw54 = 0;
  double fw55 = 0;
  double fw56 = 0;
  double fw57 = 0;
  double fw58 = 0;
  double fw59 = 0;
  double fw60 = 0;
  double fw61 = 0;
  double fw62 = 0;
  double fw63 = 0;
  double fw64 = 0;
  double fw65 = 0;
  double fw66 = 0;
  double fw67 = 0;
  double fw68 = 0;
  double fw69 = 0;
  double fw70 = 0;
  double fw71 = 0;
  double fw72 = 0;
  double fw73 = 0;
  double fw74 = 0;
  double fw75 = 0;
  double fw76 = 0;
  double fw77 = 0;
  double fw78 = 0;
  double fw79 = 0;
  double fw80 = 0;
  {
    fw0 = sp_421_486 * weights_421[iq];
    fw1 = sp_421_495 * weights_421[iq];
    fw2 = sp_421_504 * weights_421[iq];
    fw3 = sp_421_487 * weights_421[iq];
    fw4 = sp_421_496 * weights_421[iq];
    fw5 = sp_421_505 * weights_421[iq];
    fw6 = sp_421_488 * weights_421[iq];
    fw7 = sp_421_497 * weights_421[iq];
    fw8 = sp_421_506 * weights_421[iq];
    fw9 = sp_421_513 * weights_421[iq];
    fw10 = sp_421_522 * weights_421[iq];
    fw11 = sp_421_531 * weights_421[iq];
    fw12 = sp_421_514 * weights_421[iq];
    fw13 = sp_421_523 * weights_421[iq];
    fw14 = sp_421_532 * weights_421[iq];
    fw15 = sp_421_515 * weights_421[iq];
    fw16 = sp_421_524 * weights_421[iq];
    fw17 = sp_421_533 * weights_421[iq];
    fw18 = sp_421_540 * weights_421[iq];
    fw19 = sp_421_549 * weights_421[iq];
    fw20 = sp_421_558 * weights_421[iq];
    fw21 = sp_421_541 * weights_421[iq];
    fw22 = sp_421_550 * weights_421[iq];
    fw23 = sp_421_559 * weights_421[iq];
    fw24 = sp_421_542 * weights_421[iq];
    fw25 = sp_421_551 * weights_421[iq];
    fw26 = sp_421_560 * weights_421[iq];
    fw27 = sp_421_489 * weights_421[iq];
    fw28 = sp_421_498 * weights_421[iq];
    fw29 = sp_421_507 * weights_421[iq];
    fw30 = sp_421_490 * weights_421[iq];
    fw31 = sp_421_499 * weights_421[iq];
    fw32 = sp_421_508 * weights_421[iq];
    fw33 = sp_421_491 * weights_421[iq];
    fw34 = sp_421_500 * weights_421[iq];
    fw35 = sp_421_509 * weights_421[iq];
    fw36 = sp_421_516 * weights_421[iq];
    fw37 = sp_421_525 * weights_421[iq];
    fw38 = sp_421_534 * weights_421[iq];
    fw39 = sp_421_517 * weights_421[iq];
    fw40 = sp_421_526 * weights_421[iq];
    fw41 = sp_421_535 * weights_421[iq];
    fw42 = sp_421_518 * weights_421[iq];
    fw43 = sp_421_527 * weights_421[iq];
    fw44 = sp_421_536 * weights_421[iq];
    fw45 = sp_421_543 * weights_421[iq];
    fw46 = sp_421_552 * weights_421[iq];
    fw47 = sp_421_561 * weights_421[iq];
    fw48 = sp_421_544 * weights_421[iq];
    fw49 = sp_421_553 * weights_421[iq];
    fw50 = sp_421_562 * weights_421[iq];
    fw51 = sp_421_545 * weights_421[iq];
    fw52 = sp_421_554 * weights_421[iq];
    fw53 = sp_421_563 * weights_421[iq];
    fw54 = sp_421_492 * weights_421[iq];
    fw55 = sp_421_501 * weights_421[iq];
    fw56 = sp_421_510 * weights_421[iq];
    fw57 = sp_421_493 * weights_421[iq];
    fw58 = sp_421_502 * weights_421[iq];
    fw59 = sp_421_511 * weights_421[iq];
    fw60 = sp_421_494 * weights_421[iq];
    fw61 = sp_421_503 * weights_421[iq];
    fw62 = sp_421_512 * weights_421[iq];
    fw63 = sp_421_519 * weights_421[iq];
    fw64 = sp_421_528 * weights_421[iq];
    fw65 = sp_421_537 * weights_421[iq];
    fw66 = sp_421_520 * weights_421[iq];
    fw67 = sp_421_529 * weights_421[iq];
    fw68 = sp_421_538 * weights_421[iq];
    fw69 = sp_421_521 * weights_421[iq];
    fw70 = sp_421_530 * weights_421[iq];
    fw71 = sp_421_539 * weights_421[iq];
    fw72 = sp_421_546 * weights_421[iq];
    fw73 = sp_421_555 * weights_421[iq];
    fw74 = sp_421_564 * weights_421[iq];
    fw75 = sp_421_547 * weights_421[iq];
    fw76 = sp_421_556 * weights_421[iq];
    fw77 = sp_421_565 * weights_421[iq];
    fw78 = sp_421_548 * weights_421[iq];
    fw79 = sp_421_557 * weights_421[iq];
    fw80 = sp_421_566 * weights_421[iq];
  }
  // ------------------------ 
  // ------------------------ 
  // Section: Tensor Computation
  // Inputs: fw34, fw75, fw77, fw65, fw57, fw13, fw78, fw44, fw7, fw58, fw5, fw67, fw6, fw31, fw72, fw76, fw42, fw21, fw36, fw23, fw10, FE3_C0_D100_Q421, fw0, fw19, fw20, fw8, fw2, fw33, fw29, fw66, fw18, fw52, fw74, fw3, fw45, fw71, fw69, fw9, fw51, fw41, fw37, fw25, fw80, fw30, fw40, fw47, fw55, fw17, fw62, fw43, fw27, fw11, fw53, fw63, fw22, fw46, fw49, fw54, fw38, fw56, fw73, fw15, fw48, fw26, FE1_C2_D001_Q421, fw4, fw60, fw14, fw28, fw59, fw12, fw70, fw24, fw64, fw39, fw79, fw61, fw68, fw32, fw50, fw35, FE1_C1_D010_Q421, fw16, fw1
  // Outputs: A
  {
    double temp_0[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_0[j] = fw0 * FE3_C0_D100_Q421[0][0][0][j];
    }
    double temp_1[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_1[j] = fw1 * FE1_C1_D010_Q421[0][0][0][j];
    }
    double temp_2[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_2[j] = fw2 * FE1_C2_D001_Q421[0][0][0][j];
    }
    double temp_3[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_3[j] = fw3 * FE3_C0_D100_Q421[0][0][0][j];
    }
    double temp_4[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_4[j] = fw4 * FE1_C1_D010_Q421[0][0][0][j];
    }
    double temp_5[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_5[j] = fw5 * FE1_C2_D001_Q421[0][0][0][j];
    }
    double temp_6[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_6[j] = fw6 * FE3_C0_D100_Q421[0][0][0][j];
    }
    double temp_7[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_7[j] = fw7 * FE1_C1_D010_Q421[0][0][0][j];
    }
    double temp_8[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_8[j] = fw8 * FE1_C2_D001_Q421[0][0][0][j];
    }
    double temp_9[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_9[j] = fw9 * FE3_C0_D100_Q421[0][0][0][j];
    }
    double temp_10[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_10[j] = fw10 * FE1_C1_D010_Q421[0][0][0][j];
    }
    double temp_11[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_11[j] = fw11 * FE1_C2_D001_Q421[0][0][0][j];
    }
    double temp_12[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_12[j] = fw12 * FE3_C0_D100_Q421[0][0][0][j];
    }
    double temp_13[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_13[j] = fw13 * FE1_C1_D010_Q421[0][0][0][j];
    }
    double temp_14[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_14[j] = fw14 * FE1_C2_D001_Q421[0][0][0][j];
    }
    double temp_15[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_15[j] = fw15 * FE3_C0_D100_Q421[0][0][0][j];
    }
    double temp_16[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_16[j] = fw16 * FE1_C1_D010_Q421[0][0][0][j];
    }
    double temp_17[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_17[j] = fw17 * FE1_C2_D001_Q421[0][0][0][j];
    }
    double temp_18[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_18[j] = fw18 * FE3_C0_D100_Q421[0][0][0][j];
    }
    double temp_19[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_19[j] = fw19 * FE1_C1_D010_Q421[0][0][0][j];
    }
    double temp_20[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_20[j] = fw20 * FE1_C2_D001_Q421[0][0][0][j];
    }
    double temp_21[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_21[j] = fw21 * FE3_C0_D100_Q421[0][0][0][j];
    }
    double temp_22[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_22[j] = fw22 * FE1_C1_D010_Q421[0][0][0][j];
    }
    double temp_23[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_23[j] = fw23 * FE1_C2_D001_Q421[0][0][0][j];
    }
    double temp_24[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_24[j] = fw24 * FE3_C0_D100_Q421[0][0][0][j];
    }
    double temp_25[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_25[j] = fw25 * FE1_C1_D010_Q421[0][0][0][j];
    }
    double temp_26[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_26[j] = fw26 * FE1_C2_D001_Q421[0][0][0][j];
    }
    double temp_27[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_27[j] = fw27 * FE3_C0_D100_Q421[0][0][0][j];
    }
    double temp_28[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_28[j] = fw28 * FE1_C1_D010_Q421[0][0][0][j];
    }
    double temp_29[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_29[j] = fw29 * FE1_C2_D001_Q421[0][0][0][j];
    }
    double temp_30[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_30[j] = fw30 * FE3_C0_D100_Q421[0][0][0][j];
    }
    double temp_31[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_31[j] = fw31 * FE1_C1_D010_Q421[0][0][0][j];
    }
    double temp_32[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_32[j] = fw32 * FE1_C2_D001_Q421[0][0][0][j];
    }
    double temp_33[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_33[j] = fw33 * FE3_C0_D100_Q421[0][0][0][j];
    }
    double temp_34[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_34[j] = fw34 * FE1_C1_D010_Q421[0][0][0][j];
    }
    double temp_35[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_35[j] = fw35 * FE1_C2_D001_Q421[0][0][0][j];
    }
    double temp_36[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_36[j] = fw36 * FE3_C0_D100_Q421[0][0][0][j];
    }
    double temp_37[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_37[j] = fw37 * FE1_C1_D010_Q421[0][0][0][j];
    }
    double temp_38[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_38[j] = fw38 * FE1_C2_D001_Q421[0][0][0][j];
    }
    double temp_39[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_39[j] = fw39 * FE3_C0_D100_Q421[0][0][0][j];
    }
    double temp_40[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_40[j] = fw40 * FE1_C1_D010_Q421[0][0][0][j];
    }
    double temp_41[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_41[j] = fw41 * FE1_C2_D001_Q421[0][0][0][j];
    }
    double temp_42[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_42[j] = fw42 * FE3_C0_D100_Q421[0][0][0][j];
    }
    double temp_43[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_43[j] = fw43 * FE1_C1_D010_Q421[0][0][0][j];
    }
    double temp_44[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_44[j] = fw44 * FE1_C2_D001_Q421[0][0][0][j];
    }
    double temp_45[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_45[j] = fw45 * FE3_C0_D100_Q421[0][0][0][j];
    }
    double temp_46[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_46[j] = fw46 * FE1_C1_D010_Q421[0][0][0][j];
    }
    double temp_47[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_47[j] = fw47 * FE1_C2_D001_Q421[0][0][0][j];
    }
    double temp_48[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_48[j] = fw48 * FE3_C0_D100_Q421[0][0][0][j];
    }
    double temp_49[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_49[j] = fw49 * FE1_C1_D010_Q421[0][0][0][j];
    }
    double temp_50[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_50[j] = fw50 * FE1_C2_D001_Q421[0][0][0][j];
    }
    double temp_51[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_51[j] = fw51 * FE3_C0_D100_Q421[0][0][0][j];
    }
    double temp_52[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_52[j] = fw52 * FE1_C1_D010_Q421[0][0][0][j];
    }
    double temp_53[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_53[j] = fw53 * FE1_C2_D001_Q421[0][0][0][j];
    }
    double temp_54[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_54[j] = fw54 * FE3_C0_D100_Q421[0][0][0][j];
    }
    double temp_55[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_55[j] = fw55 * FE1_C1_D010_Q421[0][0][0][j];
    }
    double temp_56[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_56[j] = fw56 * FE1_C2_D001_Q421[0][0][0][j];
    }
    double temp_57[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_57[j] = fw57 * FE3_C0_D100_Q421[0][0][0][j];
    }
    double temp_58[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_58[j] = fw58 * FE1_C1_D010_Q421[0][0][0][j];
    }
    double temp_59[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_59[j] = fw59 * FE1_C2_D001_Q421[0][0][0][j];
    }
    double temp_60[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_60[j] = fw60 * FE3_C0_D100_Q421[0][0][0][j];
    }
    double temp_61[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_61[j] = fw61 * FE1_C1_D010_Q421[0][0][0][j];
    }
    double temp_62[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_62[j] = fw62 * FE1_C2_D001_Q421[0][0][0][j];
    }
    double temp_63[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_63[j] = fw63 * FE3_C0_D100_Q421[0][0][0][j];
    }
    double temp_64[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_64[j] = fw64 * FE1_C1_D010_Q421[0][0][0][j];
    }
    double temp_65[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_65[j] = fw65 * FE1_C2_D001_Q421[0][0][0][j];
    }
    double temp_66[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_66[j] = fw66 * FE3_C0_D100_Q421[0][0][0][j];
    }
    double temp_67[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_67[j] = fw67 * FE1_C1_D010_Q421[0][0][0][j];
    }
    double temp_68[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_68[j] = fw68 * FE1_C2_D001_Q421[0][0][0][j];
    }
    double temp_69[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_69[j] = fw69 * FE3_C0_D100_Q421[0][0][0][j];
    }
    double temp_70[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_70[j] = fw70 * FE1_C1_D010_Q421[0][0][0][j];
    }
    double temp_71[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_71[j] = fw71 * FE1_C2_D001_Q421[0][0][0][j];
    }
    double temp_72[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_72[j] = fw72 * FE3_C0_D100_Q421[0][0][0][j];
    }
    double temp_73[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_73[j] = fw73 * FE1_C1_D010_Q421[0][0][0][j];
    }
    double temp_74[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_74[j] = fw74 * FE1_C2_D001_Q421[0][0][0][j];
    }
    double temp_75[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_75[j] = fw75 * FE3_C0_D100_Q421[0][0][0][j];
    }
    double temp_76[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_76[j] = fw76 * FE1_C1_D010_Q421[0][0][0][j];
    }
    double temp_77[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_77[j] = fw77 * FE1_C2_D001_Q421[0][0][0][j];
    }
    double temp_78[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_78[j] = fw78 * FE3_C0_D100_Q421[0][0][0][j];
    }
    double temp_79[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_79[j] = fw79 * FE1_C1_D010_Q421[0][0][0][j];
    }
    double temp_80[4] = {0};
    for (int j = 0; j < 4; ++j)
    {
      temp_80[j] = fw80 * FE1_C2_D001_Q421[0][0][0][j];
    }
    for (int j = 0; j < 4; ++j)
    {
      for (int i = 0; i < 4; ++i)
      {
        A[12 * (3 * (i)) + 3 * (j)] += FE3_C0_D100_Q421[0][0][0][i] * temp_0[j];
        A[12 * (3 * (i)) + 3 * (j)] += FE3_C0_D100_Q421[0][0][0][i] * temp_1[j];
        A[12 * (3 * (i)) + 3 * (j)] += FE3_C0_D100_Q421[0][0][0][i] * temp_2[j];
        A[12 * (3 * (i)) + 3 * (j)] += FE1_C1_D010_Q421[0][0][0][i] * temp_3[j];
        A[12 * (3 * (i)) + 3 * (j)] += FE1_C1_D010_Q421[0][0][0][i] * temp_4[j];
        A[12 * (3 * (i)) + 3 * (j)] += FE1_C1_D010_Q421[0][0][0][i] * temp_5[j];
        A[12 * (3 * (i)) + 3 * (j)] += FE1_C2_D001_Q421[0][0][0][i] * temp_6[j];
        A[12 * (3 * (i)) + 3 * (j)] += FE1_C2_D001_Q421[0][0][0][i] * temp_7[j];
        A[12 * (3 * (i)) + 3 * (j)] += FE1_C2_D001_Q421[0][0][0][i] * temp_8[j];
        A[12 * (3 * (i)) + (3 * (j) + 1)] += FE3_C0_D100_Q421[0][0][0][i] * temp_9[j];
        A[12 * (3 * (i)) + (3 * (j) + 1)] += FE3_C0_D100_Q421[0][0][0][i] * temp_10[j];
        A[12 * (3 * (i)) + (3 * (j) + 1)] += FE3_C0_D100_Q421[0][0][0][i] * temp_11[j];
        A[12 * (3 * (i)) + (3 * (j) + 1)] += FE1_C1_D010_Q421[0][0][0][i] * temp_12[j];
        A[12 * (3 * (i)) + (3 * (j) + 1)] += FE1_C1_D010_Q421[0][0][0][i] * temp_13[j];
        A[12 * (3 * (i)) + (3 * (j) + 1)] += FE1_C1_D010_Q421[0][0][0][i] * temp_14[j];
        A[12 * (3 * (i)) + (3 * (j) + 1)] += FE1_C2_D001_Q421[0][0][0][i] * temp_15[j];
        A[12 * (3 * (i)) + (3 * (j) + 1)] += FE1_C2_D001_Q421[0][0][0][i] * temp_16[j];
        A[12 * (3 * (i)) + (3 * (j) + 1)] += FE1_C2_D001_Q421[0][0][0][i] * temp_17[j];
        A[12 * (3 * (i)) + (3 * (j) + 2)] += FE3_C0_D100_Q421[0][0][0][i] * temp_18[j];
        A[12 * (3 * (i)) + (3 * (j) + 2)] += FE3_C0_D100_Q421[0][0][0][i] * temp_19[j];
        A[12 * (3 * (i)) + (3 * (j) + 2)] += FE3_C0_D100_Q421[0][0][0][i] * temp_20[j];
        A[12 * (3 * (i)) + (3 * (j) + 2)] += FE1_C1_D010_Q421[0][0][0][i] * temp_21[j];
        A[12 * (3 * (i)) + (3 * (j) + 2)] += FE1_C1_D010_Q421[0][0][0][i] * temp_22[j];
        A[12 * (3 * (i)) + (3 * (j) + 2)] += FE1_C1_D010_Q421[0][0][0][i] * temp_23[j];
        A[12 * (3 * (i)) + (3 * (j) + 2)] += FE1_C2_D001_Q421[0][0][0][i] * temp_24[j];
        A[12 * (3 * (i)) + (3 * (j) + 2)] += FE1_C2_D001_Q421[0][0][0][i] * temp_25[j];
        A[12 * (3 * (i)) + (3 * (j) + 2)] += FE1_C2_D001_Q421[0][0][0][i] * temp_26[j];
        A[12 * (3 * (i) + 1) + 3 * (j)] += FE3_C0_D100_Q421[0][0][0][i] * temp_27[j];
        A[12 * (3 * (i) + 1) + 3 * (j)] += FE3_C0_D100_Q421[0][0][0][i] * temp_28[j];
        A[12 * (3 * (i) + 1) + 3 * (j)] += FE3_C0_D100_Q421[0][0][0][i] * temp_29[j];
        A[12 * (3 * (i) + 1) + 3 * (j)] += FE1_C1_D010_Q421[0][0][0][i] * temp_30[j];
        A[12 * (3 * (i) + 1) + 3 * (j)] += FE1_C1_D010_Q421[0][0][0][i] * temp_31[j];
        A[12 * (3 * (i) + 1) + 3 * (j)] += FE1_C1_D010_Q421[0][0][0][i] * temp_32[j];
        A[12 * (3 * (i) + 1) + 3 * (j)] += FE1_C2_D001_Q421[0][0][0][i] * temp_33[j];
        A[12 * (3 * (i) + 1) + 3 * (j)] += FE1_C2_D001_Q421[0][0][0][i] * temp_34[j];
        A[12 * (3 * (i) + 1) + 3 * (j)] += FE1_C2_D001_Q421[0][0][0][i] * temp_35[j];
        A[12 * (3 * (i) + 1) + (3 * (j) + 1)] += FE3_C0_D100_Q421[0][0][0][i] * temp_36[j];
        A[12 * (3 * (i) + 1) + (3 * (j) + 1)] += FE3_C0_D100_Q421[0][0][0][i] * temp_37[j];
        A[12 * (3 * (i) + 1) + (3 * (j) + 1)] += FE3_C0_D100_Q421[0][0][0][i] * temp_38[j];
        A[12 * (3 * (i) + 1) + (3 * (j) + 1)] += FE1_C1_D010_Q421[0][0][0][i] * temp_39[j];
        A[12 * (3 * (i) + 1) + (3 * (j) + 1)] += FE1_C1_D010_Q421[0][0][0][i] * temp_40[j];
        A[12 * (3 * (i) + 1) + (3 * (j) + 1)] += FE1_C1_D010_Q421[0][0][0][i] * temp_41[j];
        A[12 * (3 * (i) + 1) + (3 * (j) + 1)] += FE1_C2_D001_Q421[0][0][0][i] * temp_42[j];
        A[12 * (3 * (i) + 1) + (3 * (j) + 1)] += FE1_C2_D001_Q421[0][0][0][i] * temp_43[j];
        A[12 * (3 * (i) + 1) + (3 * (j) + 1)] += FE1_C2_D001_Q421[0][0][0][i] * temp_44[j];
        A[12 * (3 * (i) + 1) + (3 * (j) + 2)] += FE3_C0_D100_Q421[0][0][0][i] * temp_45[j];
        A[12 * (3 * (i) + 1) + (3 * (j) + 2)] += FE3_C0_D100_Q421[0][0][0][i] * temp_46[j];
        A[12 * (3 * (i) + 1) + (3 * (j) + 2)] += FE3_C0_D100_Q421[0][0][0][i] * temp_47[j];
        A[12 * (3 * (i) + 1) + (3 * (j) + 2)] += FE1_C1_D010_Q421[0][0][0][i] * temp_48[j];
        A[12 * (3 * (i) + 1) + (3 * (j) + 2)] += FE1_C1_D010_Q421[0][0][0][i] * temp_49[j];
        A[12 * (3 * (i) + 1) + (3 * (j) + 2)] += FE1_C1_D010_Q421[0][0][0][i] * temp_50[j];
        A[12 * (3 * (i) + 1) + (3 * (j) + 2)] += FE1_C2_D001_Q421[0][0][0][i] * temp_51[j];
        A[12 * (3 * (i) + 1) + (3 * (j) + 2)] += FE1_C2_D001_Q421[0][0][0][i] * temp_52[j];
        A[12 * (3 * (i) + 1) + (3 * (j) + 2)] += FE1_C2_D001_Q421[0][0][0][i] * temp_53[j];
        A[12 * (3 * (i) + 2) + 3 * (j)] += FE3_C0_D100_Q421[0][0][0][i] * temp_54[j];
        A[12 * (3 * (i) + 2) + 3 * (j)] += FE3_C0_D100_Q421[0][0][0][i] * temp_55[j];
        A[12 * (3 * (i) + 2) + 3 * (j)] += FE3_C0_D100_Q421[0][0][0][i] * temp_56[j];
        A[12 * (3 * (i) + 2) + 3 * (j)] += FE1_C1_D010_Q421[0][0][0][i] * temp_57[j];
        A[12 * (3 * (i) + 2) + 3 * (j)] += FE1_C1_D010_Q421[0][0][0][i] * temp_58[j];
        A[12 * (3 * (i) + 2) + 3 * (j)] += FE1_C1_D010_Q421[0][0][0][i] * temp_59[j];
        A[12 * (3 * (i) + 2) + 3 * (j)] += FE1_C2_D001_Q421[0][0][0][i] * temp_60[j];
        A[12 * (3 * (i) + 2) + 3 * (j)] += FE1_C2_D001_Q421[0][0][0][i] * temp_61[j];
        A[12 * (3 * (i) + 2) + 3 * (j)] += FE1_C2_D001_Q421[0][0][0][i] * temp_62[j];
        A[12 * (3 * (i) + 2) + (3 * (j) + 1)] += FE3_C0_D100_Q421[0][0][0][i] * temp_63[j];
        A[12 * (3 * (i) + 2) + (3 * (j) + 1)] += FE3_C0_D100_Q421[0][0][0][i] * temp_64[j];
        A[12 * (3 * (i) + 2) + (3 * (j) + 1)] += FE3_C0_D100_Q421[0][0][0][i] * temp_65[j];
        A[12 * (3 * (i) + 2) + (3 * (j) + 1)] += FE1_C1_D010_Q421[0][0][0][i] * temp_66[j];
        A[12 * (3 * (i) + 2) + (3 * (j) + 1)] += FE1_C1_D010_Q421[0][0][0][i] * temp_67[j];
        A[12 * (3 * (i) + 2) + (3 * (j) + 1)] += FE1_C1_D010_Q421[0][0][0][i] * temp_68[j];
        A[12 * (3 * (i) + 2) + (3 * (j) + 1)] += FE1_C2_D001_Q421[0][0][0][i] * temp_69[j];
        A[12 * (3 * (i) + 2) + (3 * (j) + 1)] += FE1_C2_D001_Q421[0][0][0][i] * temp_70[j];
        A[12 * (3 * (i) + 2) + (3 * (j) + 1)] += FE1_C2_D001_Q421[0][0][0][i] * temp_71[j];
        A[12 * (3 * (i) + 2) + (3 * (j) + 2)] += FE3_C0_D100_Q421[0][0][0][i] * temp_72[j];
        A[12 * (3 * (i) + 2) + (3 * (j) + 2)] += FE3_C0_D100_Q421[0][0][0][i] * temp_73[j];
        A[12 * (3 * (i) + 2) + (3 * (j) + 2)] += FE3_C0_D100_Q421[0][0][0][i] * temp_74[j];
        A[12 * (3 * (i) + 2) + (3 * (j) + 2)] += FE1_C1_D010_Q421[0][0][0][i] * temp_75[j];
        A[12 * (3 * (i) + 2) + (3 * (j) + 2)] += FE1_C1_D010_Q421[0][0][0][i] * temp_76[j];
        A[12 * (3 * (i) + 2) + (3 * (j) + 2)] += FE1_C1_D010_Q421[0][0][0][i] * temp_77[j];
        A[12 * (3 * (i) + 2) + (3 * (j) + 2)] += FE1_C2_D001_Q421[0][0][0][i] * temp_78[j];
        A[12 * (3 * (i) + 2) + (3 * (j) + 2)] += FE1_C2_D001_Q421[0][0][0][i] * temp_79[j];
        A[12 * (3 * (i) + 2) + (3 * (j) + 2)] += FE1_C2_D001_Q421[0][0][0][i] * temp_80[j];
      }
    }
  }
  // ------------------------ 
}

}



ufcx_integral integral_bb392318a7cdd42062be8c861fa77bdd276a68ca =
{
  .enabled_coefficients = NULL,
  .tabulate_tensor_float32 = NULL,
  .tabulate_tensor_float64 = tabulate_tensor_integral_bb392318a7cdd42062be8c861fa77bdd276a68ca,
  .tabulate_tensor_complex64 = NULL,
  .tabulate_tensor_complex128 = NULL,
  .needs_facet_permutations = false,
  .coordinate_element_hash = UINT64_C(0),
};

// End of code for integral integral_bb392318a7cdd42062be8c861fa77bdd276a68ca

// Code for form form_d579276cb0aa5e9ecbe08537946b2440836efda8


uint64_t finite_element_hashes_form_d579276cb0aa5e9ecbe08537946b2440836efda8[2] = {UINT64_C(0), UINT64_C(0)};
int form_integral_offsets_form_d579276cb0aa5e9ecbe08537946b2440836efda8[4] = {0, 1, 1, 1};
static ufcx_integral* form_integrals_form_d579276cb0aa5e9ecbe08537946b2440836efda8[1] = {&integral_bb392318a7cdd42062be8c861fa77bdd276a68ca};
int form_integral_ids_form_d579276cb0aa5e9ecbe08537946b2440836efda8[1] = {-1};




ufcx_form form_d579276cb0aa5e9ecbe08537946b2440836efda8 =
{

  .signature = "f005d033ea12fc272797eb132a697742213304e786890994b260898ffc527934aeb233c0785013cd3aef3f5b1f13965cf4414ddb6b75c191872f7763be8cacde",
  .rank = 2,
  .num_coefficients = 0,
  .num_constants = 0,
  .original_coefficient_positions = NULL,

  .coefficient_name_map = NULL,
  .constant_name_map = NULL,

  .finite_element_hashes = finite_element_hashes_form_d579276cb0aa5e9ecbe08537946b2440836efda8,

  .form_integrals = form_integrals_form_d579276cb0aa5e9ecbe08537946b2440836efda8,
  .form_integral_ids = form_integral_ids_form_d579276cb0aa5e9ecbe08537946b2440836efda8,
  .form_integral_offsets = form_integral_offsets_form_d579276cb0aa5e9ecbe08537946b2440836efda8
};

// Alias name
ufcx_form* form_libffcx_forms_a81e140c1e562b184b9c89c419fe2ba8c428672a_0 = &form_d579276cb0aa5e9ecbe08537946b2440836efda8;

// End of code for form form_d579276cb0aa5e9ecbe08537946b2440836efda8


/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 55), // void()(double *, double const *, double const *, double const *, int const *, uint8_t const *)
/*  1 */ _CFFI_OP(_CFFI_OP_POINTER, 38), // double *
/*  2 */ _CFFI_OP(_CFFI_OP_POINTER, 38), // double const *
/*  3 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/*  4 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/*  5 */ _CFFI_OP(_CFFI_OP_POINTER, 42), // int const *
/*  6 */ _CFFI_OP(_CFFI_OP_POINTER, 50), // uint8_t const *
/*  7 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  8 */ _CFFI_OP(_CFFI_OP_FUNCTION, 55), // void()(double _Complex *, double _Complex const *, double _Complex const *, double const *, int const *, uint8_t const *)
/*  9 */ _CFFI_OP(_CFFI_OP_POINTER, 37), // double _Complex *
/* 10 */ _CFFI_OP(_CFFI_OP_POINTER, 37), // double _Complex const *
/* 11 */ _CFFI_OP(_CFFI_OP_NOOP, 10),
/* 12 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/* 13 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 14 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 15 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 16 */ _CFFI_OP(_CFFI_OP_FUNCTION, 55), // void()(float *, float const *, float const *, float const *, int const *, uint8_t const *)
/* 17 */ _CFFI_OP(_CFFI_OP_POINTER, 40), // float *
/* 18 */ _CFFI_OP(_CFFI_OP_POINTER, 40), // float const *
/* 19 */ _CFFI_OP(_CFFI_OP_NOOP, 18),
/* 20 */ _CFFI_OP(_CFFI_OP_NOOP, 18),
/* 21 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 22 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 23 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 24 */ _CFFI_OP(_CFFI_OP_FUNCTION, 55), // void()(float _Complex *, float _Complex const *, float _Complex const *, float const *, int const *, uint8_t const *)
/* 25 */ _CFFI_OP(_CFFI_OP_POINTER, 39), // float _Complex *
/* 26 */ _CFFI_OP(_CFFI_OP_POINTER, 39), // float _Complex const *
/* 27 */ _CFFI_OP(_CFFI_OP_NOOP, 26),
/* 28 */ _CFFI_OP(_CFFI_OP_NOOP, 18),
/* 29 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 30 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 31 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 32 */ _CFFI_OP(_CFFI_OP_POINTER, 33), // _Bool const *
/* 33 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1), // _Bool
/* 34 */ _CFFI_OP(_CFFI_OP_POINTER, 35), // char const * *
/* 35 */ _CFFI_OP(_CFFI_OP_POINTER, 36), // char const *
/* 36 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
/* 37 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 49), // double _Complex
/* 38 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14), // double
/* 39 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 48), // float _Complex
/* 40 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 13), // float
/* 41 */ _CFFI_OP(_CFFI_OP_POINTER, 42), // int *
/* 42 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/* 43 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // ufcx_form
/* 44 */ _CFFI_OP(_CFFI_OP_POINTER, 45), // ufcx_integral * *
/* 45 */ _CFFI_OP(_CFFI_OP_POINTER, 46), // ufcx_integral *
/* 46 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 1), // ufcx_integral
/* 47 */ _CFFI_OP(_CFFI_OP_ENUM, 0), // ufcx_integral_type
/* 48 */ _CFFI_OP(_CFFI_OP_POINTER, 49), // uint64_t *
/* 49 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 24), // uint64_t
/* 50 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 18), // uint8_t
/* 51 */ _CFFI_OP(_CFFI_OP_POINTER, 0), // void(*)(double *, double const *, double const *, double const *, int const *, uint8_t const *)
/* 52 */ _CFFI_OP(_CFFI_OP_POINTER, 8), // void(*)(double _Complex *, double _Complex const *, double _Complex const *, double const *, int const *, uint8_t const *)
/* 53 */ _CFFI_OP(_CFFI_OP_POINTER, 16), // void(*)(float *, float const *, float const *, float const *, int const *, uint8_t const *)
/* 54 */ _CFFI_OP(_CFFI_OP_POINTER, 24), // void(*)(float _Complex *, float _Complex const *, float _Complex const *, float const *, int const *, uint8_t const *)
/* 55 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static int _cffi_const_cell(unsigned long long *o)
{
  int n = (cell) <= 0;
  *o = (unsigned long long)((cell) | 0);  /* check that cell is an integer */
  return n;
}

static int _cffi_const_exterior_facet(unsigned long long *o)
{
  int n = (exterior_facet) <= 0;
  *o = (unsigned long long)((exterior_facet) | 0);  /* check that exterior_facet is an integer */
  return n;
}

static int _cffi_const_interior_facet(unsigned long long *o)
{
  int n = (interior_facet) <= 0;
  *o = (unsigned long long)((interior_facet) | 0);  /* check that interior_facet is an integer */
  return n;
}

_CFFI_UNUSED_FN
static void _cffi_checkfld__ufcx_form(ufcx_form *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { char const * *tmp = &p->signature; (void)tmp; }
  (void)((p->rank) | 0);  /* check that 'ufcx_form.rank' is an integer */
  (void)((p->num_coefficients) | 0);  /* check that 'ufcx_form.num_coefficients' is an integer */
  (void)((p->num_constants) | 0);  /* check that 'ufcx_form.num_constants' is an integer */
  { int * *tmp = &p->original_coefficient_positions; (void)tmp; }
  { char const * * *tmp = &p->coefficient_name_map; (void)tmp; }
  { char const * * *tmp = &p->constant_name_map; (void)tmp; }
  { uint64_t * *tmp = &p->finite_element_hashes; (void)tmp; }
  { ufcx_integral * * *tmp = &p->form_integrals; (void)tmp; }
  { int * *tmp = &p->form_integral_ids; (void)tmp; }
  { int * *tmp = &p->form_integral_offsets; (void)tmp; }
}
struct _cffi_align__ufcx_form { char x; ufcx_form y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__ufcx_integral(ufcx_integral *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { _Bool const * *tmp = &p->enabled_coefficients; (void)tmp; }
  { void(* *tmp)(float *, float const *, float const *, float const *, int const *, uint8_t const *) = &p->tabulate_tensor_float32; (void)tmp; }
  { void(* *tmp)(double *, double const *, double const *, double const *, int const *, uint8_t const *) = &p->tabulate_tensor_float64; (void)tmp; }
  { void(* *tmp)(float _Complex *, float _Complex const *, float _Complex const *, float const *, int const *, uint8_t const *) = &p->tabulate_tensor_complex64; (void)tmp; }
  { void(* *tmp)(double _Complex *, double _Complex const *, double _Complex const *, double const *, int const *, uint8_t const *) = &p->tabulate_tensor_complex128; (void)tmp; }
  (void)((p->needs_facet_permutations) | 0);  /* check that 'ufcx_integral.needs_facet_permutations' is an integer */
  (void)((p->coordinate_element_hash) | 0);  /* check that 'ufcx_integral.coordinate_element_hash' is an integer */
}
struct _cffi_align__ufcx_integral { char x; ufcx_integral y; };

static ufcx_form *_cffi_var_form_d579276cb0aa5e9ecbe08537946b2440836efda8(void)
{
  return &(form_d579276cb0aa5e9ecbe08537946b2440836efda8);
}

static const struct _cffi_global_s _cffi_globals[] = {
  { "cell", (void *)_cffi_const_cell, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "exterior_facet", (void *)_cffi_const_exterior_facet, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "form_d579276cb0aa5e9ecbe08537946b2440836efda8", (void *)_cffi_var_form_d579276cb0aa5e9ecbe08537946b2440836efda8, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 43), (void *)0 },
  { "interior_facet", (void *)_cffi_const_interior_facet, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
};

static const struct _cffi_field_s _cffi_fields[] = {
  { "signature", offsetof(ufcx_form, signature),
                 sizeof(((ufcx_form *)0)->signature),
                 _CFFI_OP(_CFFI_OP_NOOP, 35) },
  { "rank", offsetof(ufcx_form, rank),
            sizeof(((ufcx_form *)0)->rank),
            _CFFI_OP(_CFFI_OP_NOOP, 42) },
  { "num_coefficients", offsetof(ufcx_form, num_coefficients),
                        sizeof(((ufcx_form *)0)->num_coefficients),
                        _CFFI_OP(_CFFI_OP_NOOP, 42) },
  { "num_constants", offsetof(ufcx_form, num_constants),
                     sizeof(((ufcx_form *)0)->num_constants),
                     _CFFI_OP(_CFFI_OP_NOOP, 42) },
  { "original_coefficient_positions", offsetof(ufcx_form, original_coefficient_positions),
                                      sizeof(((ufcx_form *)0)->original_coefficient_positions),
                                      _CFFI_OP(_CFFI_OP_NOOP, 41) },
  { "coefficient_name_map", offsetof(ufcx_form, coefficient_name_map),
                            sizeof(((ufcx_form *)0)->coefficient_name_map),
                            _CFFI_OP(_CFFI_OP_NOOP, 34) },
  { "constant_name_map", offsetof(ufcx_form, constant_name_map),
                         sizeof(((ufcx_form *)0)->constant_name_map),
                         _CFFI_OP(_CFFI_OP_NOOP, 34) },
  { "finite_element_hashes", offsetof(ufcx_form, finite_element_hashes),
                             sizeof(((ufcx_form *)0)->finite_element_hashes),
                             _CFFI_OP(_CFFI_OP_NOOP, 48) },
  { "form_integrals", offsetof(ufcx_form, form_integrals),
                      sizeof(((ufcx_form *)0)->form_integrals),
                      _CFFI_OP(_CFFI_OP_NOOP, 44) },
  { "form_integral_ids", offsetof(ufcx_form, form_integral_ids),
                         sizeof(((ufcx_form *)0)->form_integral_ids),
                         _CFFI_OP(_CFFI_OP_NOOP, 41) },
  { "form_integral_offsets", offsetof(ufcx_form, form_integral_offsets),
                             sizeof(((ufcx_form *)0)->form_integral_offsets),
                             _CFFI_OP(_CFFI_OP_NOOP, 41) },
  { "enabled_coefficients", offsetof(ufcx_integral, enabled_coefficients),
                            sizeof(((ufcx_integral *)0)->enabled_coefficients),
                            _CFFI_OP(_CFFI_OP_NOOP, 32) },
  { "tabulate_tensor_float32", offsetof(ufcx_integral, tabulate_tensor_float32),
                               sizeof(((ufcx_integral *)0)->tabulate_tensor_float32),
                               _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "tabulate_tensor_float64", offsetof(ufcx_integral, tabulate_tensor_float64),
                               sizeof(((ufcx_integral *)0)->tabulate_tensor_float64),
                               _CFFI_OP(_CFFI_OP_NOOP, 51) },
  { "tabulate_tensor_complex64", offsetof(ufcx_integral, tabulate_tensor_complex64),
                                 sizeof(((ufcx_integral *)0)->tabulate_tensor_complex64),
                                 _CFFI_OP(_CFFI_OP_NOOP, 54) },
  { "tabulate_tensor_complex128", offsetof(ufcx_integral, tabulate_tensor_complex128),
                                  sizeof(((ufcx_integral *)0)->tabulate_tensor_complex128),
                                  _CFFI_OP(_CFFI_OP_NOOP, 52) },
  { "needs_facet_permutations", offsetof(ufcx_integral, needs_facet_permutations),
                                sizeof(((ufcx_integral *)0)->needs_facet_permutations),
                                _CFFI_OP(_CFFI_OP_NOOP, 33) },
  { "coordinate_element_hash", offsetof(ufcx_integral, coordinate_element_hash),
                               sizeof(((ufcx_integral *)0)->coordinate_element_hash),
                               _CFFI_OP(_CFFI_OP_NOOP, 49) },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "ufcx_form", 43, _CFFI_F_CHECK_FIELDS,
    sizeof(ufcx_form), offsetof(struct _cffi_align__ufcx_form, y), 0, 11 },
  { "ufcx_integral", 46, _CFFI_F_CHECK_FIELDS,
    sizeof(ufcx_integral), offsetof(struct _cffi_align__ufcx_integral, y), 11, 7 },
};

static const struct _cffi_enum_s _cffi_enums[] = {
  { "$ufcx_integral_type", 47, _cffi_prim_int(sizeof(ufcx_integral_type), ((ufcx_integral_type)-1) <= 0),
    "cell,exterior_facet,interior_facet" },
};

static const struct _cffi_typename_s _cffi_typenames[] = {
  { "ufcx_form", 43 },
  { "ufcx_integral", 46 },
  { "ufcx_integral_type", 47 },
  { "ufcx_tabulate_tensor_complex128", 8 },
  { "ufcx_tabulate_tensor_complex64", 24 },
  { "ufcx_tabulate_tensor_float32", 16 },
  { "ufcx_tabulate_tensor_float64", 0 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  _cffi_fields,
  _cffi_struct_unions,
  _cffi_enums,
  _cffi_typenames,
  4,  /* num_globals */
  2,  /* num_struct_unions */
  1,  /* num_enums */
  7,  /* num_typenames */
  NULL,  /* no includes */
  56,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_libffcx_forms_a81e140c1e562b184b9c89c419fe2ba8c428672a(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit_libffcx_forms_a81e140c1e562b184b9c89c419fe2ba8c428672a(void) { return NULL; }
#  else
     initlibffcx_forms_a81e140c1e562b184b9c89c419fe2ba8c428672a(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit_libffcx_forms_a81e140c1e562b184b9c89c419fe2ba8c428672a(void)
{
  return _cffi_init("libffcx_forms_a81e140c1e562b184b9c89c419fe2ba8c428672a", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
initlibffcx_forms_a81e140c1e562b184b9c89c419fe2ba8c428672a(void)
{
  _cffi_init("libffcx_forms_a81e140c1e562b184b9c89c419fe2ba8c428672a", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
